### ISSUE TITLE
Christ Church records have "Title" in the title field

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#10]
This looks like a bug somewhere:

https://github.com/bodleian/medieval-mss/blob/master/collections/Christ_Church/100.xml#L8

It's the same in Matthew's repository, so assigning it to him to fix.

**Comment by jamescummings** [comment]
That is probably a legacy problem -- the idno for those used to just be a number which @holfordm had corrected. Because of that the original conversion years ago probably didn't create a good title. Ah well.

**Comment by holfordm** [comment]
I have fixed this in my repo, so the changes should be carried across when James does the next (final?) conversion
