### ISSUE TITLE
place index (as well as person index) should filter by role

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#100]
## Detailed Description
This may seem odd but since places includes organizations which have roles such as "formerOwner" (mostly) or "binder" (occasionally), it should be possible to filter by these roles, as in the persons index

## Link to Page
http://medieval-qa.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=place

## Context
Users can't currently use the filters to return all owners (or binders, etc.) since the filter applies only to the persons index

## Possible Implementation
filters as here:
http://medieval-qa.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=person

**Comment by ahankinson** [comment]
@andrew-morrison Could you look at the person roles and see if you can implement that in the places index for the Medieval catalogue? Once that's in place I will update the Blacklight app to show the facet.

**Comment by andrew-morrison** [comment]
I can easily do this for orgName elements. Of the 366 currently predefined organizations, there are 121 with the role of "formerOwner" (which is translated into "Owner or signer" for people, but perhaps just "Owner" would be better for organizations?), 4 with "binder", and one each for "patron" and "artist".

That means only about 15% of everything listed on the web site in the "Places" browser will have a role. Sometimes such under-populated filters can mislead people, if they think it's an accurate summary of what's available, when in reality it's more of a reflection of cataloguing priorities. The placeName elements don't have roles (although the schema appears to allow it) but most do have either "settlement", "region" or "country" set as their type in places.xml. Perhaps it would be more useful for the users if places got those as their roles? And the rest, with neither, a role of "Unknown"?

@ahankinson: Would "pl_roles_sm" be the correct fieldname for this?

**Comment by holfordm** [comment]
I see the problem regarding incomplete filters - the same problem applies to the persons index, in fact -- although more people have roles, not all of them do. 
I don't think it makes sense to introduce roles where they are not present; it may make sense to have a filter for placename type at some point, but that should be a separate filter, I think
Maybe the whole issue could be addressed by adding a help tooltip (apologies if that is not the correct terminology!) which if clicked on would explain that only a percentage of persons/orgs have roles. The need for tooltips (or whatever they are called) was noted at the Fihrist meeting - the Fihrist website currenlty has them in the collection statistics box http://www.fihrist.org.uk/ but they are lacking from the Medieval site currently

**Comment by andrew-morrison** [comment]
I've created some new issues to separate out the longer-term stuff. I'll go ahead and implement the Role facet on Places in the most basic way, just using orgName/@role values, and populating the pp_roles_sm index so it merges with People when in the generic search, and let you know when it is on the QA site.
