### ISSUE TITLE
Should there be any "blank" people? 

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#103]
In other words, should people in persons.xml but not (yet?) tagged anywhere in any manuscript TEI file be indexed and appear on the web site?

There are currently 25 of these, for example:

http://medieval.bodleian.ox.ac.uk/catalog/person_100170309 
http://medieval.bodleian.ox.ac.uk/catalog/person_305190695

Possibly related to #34

**Comment by andrew-morrison** [comment]
Ditto for places and works, although I haven't checked if there are any examples for those. Sorry if this has been asked before.

**Comment by holfordm** [comment]
Thanks. These are probably cases where I have updated an identifier but forgotten to change the authority file. Could you send me a list and I will check them. Also if you have a script for finding them it might be useful to have it in the repo in a new 'QA' or 'tests' directory?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ahankinson** [comment]
If at all possible I would prefer to keep scripts in the 'processing' directory, just so they're not scattered across the project.

**Comment by andrew-morrison** [comment]
I can modify the XQuery to skip over these cases, so they'll disappear from the web site, and also write to a [log file](https://github.com/bodleian/medieval-mss/files/1514697/log.txt).

So, instead of maintaining a separate script, generate-solr-document.sh would check for this (and potentially other data issues) every time you run it. Would you like it to ask you whether to proceed to the re-indexing stage if it finds anything

**Comment by holfordm** [comment]
Yes, why not

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andrew-morrison** [comment]
@holfordm: Do you work on Windows and have your own .bat scripts for running the XQuery and updating Solr? If so, they'd need a few changes for the XQuery to write to a log file. If you commit those we might be able to re-use them for other TEI catalogues.

**Comment by holfordm** [comment]
Using the git shell in Windows I can run the .sh scripts.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andrew-morrison** [comment]
@holfordm: I've committed changes to the scripts that generate the index files and send them to Solr. They fix a few bugs, this issue included, but also includes enhancements with an eye towards making the process more user-friendly for other TEI catalogues in the future.

The main change is logging of data issues while generating the Solr files. That includes the people in the authority file who aren't in any manuscripts, as discussed above, but also several other things I've noticed while familiarizing myself with both the scripts and the schema. The number and type of these is reported as they are discovered. So, if you run `index-all-qa.sh`, it will stop after generating the manuscripts index file, tell you what it has found, and ask you if you want to send it to Solr or not. It will do the same thing for each index. If you don't want that, run `index-all-qa.sh force` to return to the old behaviour (but still write to log files). Or `index-all-qa.sh noindex` will generate all the files, and the logs, but not send them to Solr. It also tests for system errors (e.g. if the Solr server is down) and displays plain-English messages instead of things like the raw responses returned from Solr.

If you could test this in your git shell environment, I'd be grateful. Let me know if it works, what's useful, what isn't, and any other potential data issues you'd think it would be useful to test for.

I'll write all this up in proper documentation very soon. Ideally, I want to get this sorted out this week and then I can just duplicate the same scripts for Fihrist, and all the others.

Sorry to push out a load of changes in one go. I'll try to make my commits much more atomic in the future.

**Comment by andrew-morrison** [comment]
Reopening for @holfordm to comment.
