### ISSUE TITLE
Should work titles starting with the word "The" be listed under "T"?

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#108]
## Detailed Description
The first letter of work titles are extracted so Solr can index them and enable the "Limit your search by letter" feature. At the moment, that's the first letter or number in the title, regardless of what the first word is.

## Link to Page
Go to Works and then click on the letter T. The [first page](http://medieval-qa.bodleian.ox.ac.uk/?f%5Balpha_title%5D%5B%5D=T&f%5Btype%5D%5B%5D=work) and a half of results are works starting with the word "The", such as "The Annals of Inisfallen" or "The Simonie" or "The story of a pope to whom his mother appeared in fiery torments because of her adultery and infanticide: he released her by a trental"

## Context
I'd expect definite and indefinite articles to be disregarded, but possibly manuscripts are different?

## Possible Implementation
Fairly simple XQuery change to strip off anything that matches a list of stop words before extracting the first letter of what remains. Any other stop words besides "The", "A" and "An"? What about [other languages](http://medieval-qa.bodleian.ox.ac.uk/?f%5Balpha_title%5D%5B%5D=L&f%5Btype%5D%5B%5D=work)?

I noticed this because the same code is used for people and places too, and I'm looking a moving such things to a central library file, used by all catalogues.

**Comment by andrew-morrison** [comment]
Yes, the display of the title would be unaffected, just assigned to a different letter of the alphabet in the index.

**Comment by andrew-morrison** [comment]
This change is now on the QA site. About 98% of the time it is an improvement (the [list of works beginning with T](http://medieval-qa.bodleian.ox.ac.uk/?f[alpha_title][]=T&f[type][]=work) is much better without all the ["the something" titles](https://medieval.bodleian.ox.ac.uk/?f%5Balpha_title%5D%5B%5D=T&f%5Btype%5D%5B%5D=work)) but there are a few counter examples. Mostly when a work begins with a person's name, and that person has a French-style surname. So [this work](http://medieval-qa.bodleian.ox.ac.uk/catalog/work_555), for example, is now [listed under "S"](http://medieval-qa.bodleian.ox.ac.uk/?f%5Balpha_title%5D%5B%5D=S&f%5Btype%5D%5B%5D=work). The [person himself](http://medieval-qa.bodleian.ox.ac.uk/catalog/person_95150005) is still listed under "L" because I haven't applied this change to any index other than works.

**Comment by holfordm** [comment]
This may get a bit complicated, but:
- if `<title type="uniform">` contains a colon `:`, then everything before the colon should be the author's name
- therefore, if the title contains a colon, don't apply the rule to ignore stopwords?
- assuming that it is most helpful to index authored works by author's name rather than by title (could they be indexed by both?)

**Comment by andrew-morrison** [comment]
I've made the change you suggest - uniform titles containing colons go back to the old method of alphabetizing, without checking for stop words first - and that results in the following works reverting back to being assigned to the following letters:

```
"L"
La Marche, Olivier de, approximately 1426-1502: Le chevalier délibéré
La Sale, Antoine de, 1385?-1461?: Le petit jehan de saintré

"T"
The story of a pope to whom his mother appeared in fiery torments because of her adultery and infanticide: he released her by a trental
```

The last one is obviously wrong, but I think this is good enough, for now.
