### ISSUE TITLE
Works not being indexed with all their languages

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#109]
## Detailed Description
I noticed while reviewing the XQuery which builds the Solr index that `@otherLangs` values in works.xml are being ignored. 

## Link to Page
The Languages filter on the [Works](https://medieval.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=work) page is missing about 600 potential work-language associations.

## Context
For example, the "French" option could return 163 more works if the ones that are predominantly in some other language, but also partially in French, were included. But was it a design decision not to include them?

## Possible Implementation
Simple XQuery change.

**Comment by holfordm** [comment]
This is an oversight; please go ahead and correct it!

**Comment by andrew-morrison** [comment]
I've fixed this, so for example [this work](http://medieval-qa.bodleian.ox.ac.uk/catalog/work_10145) is now [indexed with all four languages on QA](http://medieval-qa.bodleian.ox.ac.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=work&q=%22Alchemical+recipes+and+notes%22), as opposed to [just the mainLang on production](https://medieval.bodleian.ox.ac.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=work&q=%22Alchemical+recipes+and+notes%22) (expand the Languages filter to see the difference.)
