### ISSUE TITLE
Prevent indexing of common standard headings and labels inserted by the XSL

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#110]
This has been the case until now: everything you see on a manuscript's page on the production web site is indexed for that manuscript.

But we've found a bug (which can crash the web site if a visitor runs long phrase search queries) that requires changing the Solr configuration. That means the above stops being the case by default.

We can restore that functionality but it is worth asking if it's desirable? There are a few things that definitely seem wrong to me, such as [searching for "History" in the manuscripts index returning nearly every manuscript](https://medieval.bodleian.ox.ac.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=manuscript&q=history), because nearly every manuscript's HTML page contains a "History" subheading added by the XSLT. Also doing a [general search for your first name](https://medieval.bodleian.ox.ac.uk/?utf8=%E2%9C%93&q=matthew) returns the relevant people first, then the relevant works, followed by the manuscripts they came from, but after that thousands of manuscripts which are only matched because they have your name in the `adminInfo/recordHist/source` TEI field. That field is displayed in the HTML, as it should be, but is it something people would search for?

The alternative viewpoint is that users will be expecting to be able to search for anything they can see, because that's their experience with Google. But if you think it would be better to exclude some things from the index, it can easily be done. And it is a choice that each catalogue can make so, as with the HTML display, we can set it up to suit Medieval first, and tweak it for the others if necessary.

**Comment by andrew-morrison** [comment]
I've set up and tested a mechanism, and re-indexed on QA with the following changes to what's indexed, to demonstrate:

- All subheadings inserted by the XSLT (e.g. "History", "Physical Description", etc) are no longer indexed. This means, for example, doing a general search for _spanish history_ now returns [972 hits](http://medieval-qa.bodleian.ox.ac.uk/?utf8=%E2%9C%93&q=spanish+history) instead of the [9221 you get on the production site](https://medieval.bodleian.ox.ac.uk/?utf8=%E2%9C%93&q=spanish+history). The top matches are mostly the same (obviously production is few weeks behind) but you don't get thousands of manuscripts just because they have a "History" subheading.
- All labels inserted by the XSLT (e.g. "Language(s):", "Colophon:") are not indexed either. Some of these maybe should be indexed, for example searching for _colophon_ now return [41 hits](http://medieval-qa.bodleian.ox.ac.uk/?utf8=%E2%9C%93&q=Colophon) which is fewer than the [79 you get on production](https://medieval.bodleian.ox.ac.uk/?utf8=%E2%9C%93&q=Colophon), so it no longer finds every manuscript with colophons.

@holfordm: If you don't want this to apply to production when we update it this afternoon, it is a simple one-line change to take it out.

**Comment by holfordm** [comment]
I think I will need to get back to you about this properly in the New Year. Initial thoughts:
1. it is definitely silly to index the headings that apply to every manuscript, more or less, i.e. contents, language, physical description, form, history [and so on]
2. it is probably _not_ silly to index headings that don't apply to every manuscript _and_ which can't be filtered for or searched in other ways, for example colophon, binding.
3. it probably doesn't make sense to index the Record Source section; however, there may be a case for people wanting to find descriptions by particular people, we should find out if this is the case and if there is a better way of meeting that need.

**Comment by andrew-morrison** [comment]
OK. I'll deactivate this change for now. Here are all the subheadings, by number of occurrences, in HTML which I've just generated from the latest TEI XML:

  12525 Physical Description
  11715 Contents
  11654 History
   9188 Record Sources
   4654 Decoration
   3161 Bibliography
   3079 Online resources:   (This comes from the TEI, not inserted by XSLT)
   1071 Layout
    843 Provenance and Acquisition
    539 Binding
    535 Collation
    474 Hand(s)
    355 Digital Images
     57 Accompanying Material
     29 Condition

And here are the most common labels:

  19864 Language(s):
  11609 Support:
  11599 Origin:
  11592 Form:
   2453 Incipit:
   1776 Rubric:
   1274 Dimensions:
   1127 Extent:
    999 Explicit:
    408 Secundo Folio:
    299 Foliation:
    125 Final rubric:
    112 Musical Notation:
     75 Additions:
     59 Colophon:
      5 Seal(s):

Let me know in the New Year which would be better to exclude from the index.

**Comment by andrew-morrison** [comment]
I've also implemented a method for cataloguers to prevent indexing. But it should be considered an experimental feature, and only used in special cases. You can surround a piece of text like this...

`This will be indexed. <?noindex?>This won't be indexed.<?noindex?> This will be indexed. `

...and it will all be displayed (if it's in a TEI element which the XSL has been set up to transform into HTML) but the middle sentence won't be indexed. The use of processing instructions means it will never affect validation.

**Comment by andrew-morrison** [comment]
Fihrist has a lot of works with titles like "History of the ...", so it would be good to activate this enhancement to prevent matching every manuscript for any query containing the word history.

@holfordm: Could you take another look at the lists of headings and labels in one of my comments above? Would blocking the indexing of all those with more than 5000 occurrences be reasonable?

**Comment by ahankinson** [comment]
I find the creation of a custom processing instruction to be a leak between catalogue and implementation. Inserting values `<?noindex?>` into the XML seems to mix processing and data in a way that I would like to try and avoid, if possible. It also puts an extra burden on the cataloguer to implement.

Two possible alternate solutions, in order of ease of implementation:

1. Add the headings to the 'stop words' list in Solr. This will ensure they get filtered out or ignored in the full-text field. This is pretty easy, and since all Solr cores share the same config is something we can just do once and it will affect all catalogues.

2. Remove the headings from the fulltext search using XSLT. This will likely involve an extra processing step.

**Comment by andrew-morrison** [comment]
Using stopwords would prevent any matches for the word "History". We don't want that, just to prevent any query that includes that word from being swapped by every manuscript being matched.

The processing instructions inserted by the XSL cause the XQuery to skip over it. Those aren't included in the XML stored in GitHub, just in the HTML. But you are right that additionally giving cataloguers the option to insert processing instructions might get messy. I'll remove that extra feature, which was kind of a freebie by-product of the main aim, to prevent indexing of text added by the XSL.
