### ISSUE TITLE
unwanted whitespace after `<ex>'

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#114]
## Detailed Description
The `<ex>` tag is transformed to generate ( ) around the content of the tag, but the final ) is followed by whitespace which causes problems when (as often) the tag is in the middle of a  word and the word is broken into two sections.  

## Link to Page
For example:
MS. Holkham Gr. 1: https://medieval.bodleian.ox.ac.uk/catalog/manuscript_6116 : Contents, line 4 the TEI has `Δα<ex>υὶ</ex>δ` which appears as "Δα(υὶ) δ" (note the extra space)
MS. Holkham Gr. 15 https://medieval.bodleian.ox.ac.uk/catalog/manuscript_6136 item 25, "π(ατ) ρ(ὸ) ς" should be "π(ατ)ρ(ὸ)ς"

## Context
This does not seem to occur with similar tags, e.g. `<supplied>`.

**Comment by IgnatG** [comment]
It looks like it's coming from HTML - <span class="ex">(ὸ) </span> . It's not very visible in here but there is a space in there after the round-closing bracket. Can you check this @andrew-morrison ?

**Comment by andrew-morrison** [comment]
The space is added into the HTML by the XSL. It looks like it was set up that way for `expan` TEI elements, then `ex` were added to the same template. But the two seems to have been used in Medieval in the same contexts, so neither should be followed by a space.

@holfordm: I don't have time to test this, so could you review the next time you reindex the QA site?

**Comment by holfordm** [comment]
That makes sense - in strict TEI `<expan>` is for whole words (so makes sense to have a space after) and `<ex>` is for parts of words. But I think both are used in the Medieval catalogue for parts of words only. Ideally therefore I should fix the data and we should have different templates for each element, but that can wait.
@andrew-morrison  I should be able to check the indexing on Friday and will report back

**Comment by holfordm** [comment]
This seems to be fixed
