### ISSUE TITLE
"{character + macron}" should be normalized for search

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#115]
## Detailed Description
Currently we have some characters with macrons, mostly in transliterations from Greek; e.g. http://medieval-qa.bodleian.ox.ac.uk/catalog/person_106872042 = Morezēnos, Iōannēs -1613
A search for "Morezenos" does not return this (although it does return http://medieval-qa.bodleian.ox.ac.uk/catalog/person_2704 whose name was entered without macrons. A search for "e" should match the character with a macron as well as the plain e. (and so with other characters + macron)

## Possible Implementation
SOLR configuration issue?
Is there a way of discovering other special characters that may need normalization? š, ü seem to work OK and I guess that SOLR does most of this by default.

**Comment by andrew-morrison** [comment]
[Here is a list](https://github.com/bodleian/medieval-mss/files/1656389/non_ascii_chars_in_medieval_20180123.pdf) of non-ascii characters in Medieval's TEI files as of today.

**Comment by ahankinson** [comment]
This has been fixed in the Solr configuration.
