### ISSUE TITLE
convert2HTML: improve template rule for `<add>`

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#116]
## Detailed Description
The `<add>` element should generate appropriate symbols around the enclosed text. At some stage different symbols might be appropriate depending on the attribute for the element. For now, we might just use '`\`' before and '/' after. Thus `<add>a</add> Barbaris` > `\a/ Barbaris`

## Link to Page
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_2015

## Context
Should be relevant for all TEI catalogues

**Comment by andrew-morrison** [comment]
What about the `del` element marking deletion?

E.g. the word "bookes" on this page: http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_3917

**Comment by holfordm** [comment]
Good point. Can we use strikethrough for `del`?
For `add` I suggest:
no `@place`: \        /
`@place="above"` : ^ ^
`@place="margin"`: \    / (i.e., same as no `@place`, but we should have separate rules to make it easier to modify later if necessary)

**Comment by andrew-morrison** [comment]
@holfordm: I'll set up `add` as you suggest.

@IgnatG : `del` TEI elements are already transformed into `<span class="del">...</span>`. So some CSS could add the strike-through style that Matthew recommends (and every other catalogue will want the same). Or are `<strike>`, `<s>` or `<del>` tags now legitimate semantic elements in HTML 5 (if that's what we're conforming to)?

**Comment by IgnatG** [comment]
@andrew-morrison have a look at this: https://www.w3schools.com/tags/tag_strike.asp . <strike> is not html5 supported. So we could use <s> or <del> apparently. Otherwise I can style them in CSS

**Comment by holfordm** [comment]
@IgnatG - another question, is strikethrough text OK from a legibility / accessibility point of view or would it be better to indicate deletion in another way?

**Comment by IgnatG** [comment]
uuu... this is a weird one for screen readers as they don't support it. There are "hacks" around it... but no concrete solution in place

**Comment by andrew-morrison** [comment]
Whatever the current lack of support by screen readers for `<s>` or `<del>` HTML tags, there is at least they could be supported in the future. The non-semantic `<span class="del">` used currently will never be anything more than a way to apply styles. 

As for legibility, I guess strikeout is OK for a single word or short phrase, but it makes reading entire sentences a bit of a pain.

For now, I've set up the XSL to output `del` HTML tags for `del` TEI elements, and `ins` HTML tags for `add` TEI elements (which W3 Schools says is the equivalent, and in my browser displays as underlined.) Take another look at those examples above on QA and let us know if you're happy.
