### ISSUE TITLE
Solr failing to reindex because DocValuesField must be <= 32766

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#118]
As reported by @holfordm:

> I just tried to run index-all-qa.sh and got this log
>  
> Processing TEI files in collections folder using manuscripts.xquery on 2018-01-23 17:50:14 to be sent to solr01-qa.bodleian.ox.ac.uk for re-indexing.
> <?xml version="1.0" encoding="UTF-8"?>
> <response>
> <lst name="responseHeader"><int name="status">0</int><int name="QTime">206</int></lst>
> </response>
> curl: (22) The requested URL returned error: 400 Bad Request

**Comment by ahankinson** [comment]
That's usually caused by trying to index a field that does not exist, or does not follow the pattern for dynamic fields.

**Comment by ahankinson** [comment]
Oh, disregard my previous comment -- I see more info in the title now.

**Comment by andrew-morrison** [comment]
Checking the Solr logs, the cause was one of the manuscripts going over the 32766 limit (I think bytes rather than chars) due to lots of new notes (filled with Greek multi-byte characters). 

Those were concatenated into one long ms_textcontent_smni index field. But the same content is also indexed in the ms_textcontent_tni field, which doesn't have that limit.

Testing on QA suggests the only difference removing ms_textcontent_smni altogether makes is it no longer indexes of words joined together in that field from the end of one note and the start of the next. Which nobody will be searching for.

So the fix is to remove ms_textcontent_smni, unless there is some other reason for it.

**Comment by ahankinson** [comment]
There is a field in the Solr configuration especially for this purpose, `*_tni`. It's a non-indexed text field that is automatically copied to the fulltext index.

**Comment by ahankinson** [comment]
Ah, so the `_smni` field can be removed and all is well.
