### ISSUE TITLE
Accompanying Material

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#119]
## Detailed Description
Just stumbled across this, not sure of the details, but it seems the XSL for generating the HTML view of manuscripts has not been set up to handle `msDesc` elements inside `accMat` elements. It outputs HTML, probably mostly correctly, but it does it twice. The same content is repeated.

## Link to Page
Only seems to affect two Medieval manuscripts:

- https://medieval.bodleian.ox.ac.uk/catalog/manuscript_6297
- https://medieval.bodleian.ox.ac.uk/catalog/manuscript_3928

Corresponding to:

- Ital/MS_Ital_e_20.xml
- Christ_Church/Christ_Church_MS_140.xml

## Possible Implementation
Fixing the duplication should be a one-line change in the XSLT.

@holfordm: Presumably this is deliberate, and signifies something like fragments bound in with the manuscript at some earlier historical period? Do you have any preference for how these should be displayed?

**Comment by andrew-morrison** [comment]
Repetition fixed, and updated on QA, but presumably some layout changes are needed (e.g. the "Accompanying Material" heading made much bigger, perhaps put the entire thing in a box?)

Assigning to @holfordm to review.

**Comment by holfordm** [comment]
Thanks - will do. It may better to reorganize the entries using msPart instead of accMat - I'll let you know.
