### ISSUE TITLE
in recordhist//bibl @facs should generate live links

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#12]
lines 1133-7 of convert2HTML should include logic similar to lines 1096-1109, so that any `bibl` elements with `@facs` generate live links

**Comment by ahankinson** [comment]
If you click on the numbers on the side of the source view in GitHub you can get a link to that line in your URL. Holding shift will let you select multiple lines.

https://github.com/bodleian/medieval-mss/blob/master/processing/convert2HTML.xsl#L1096-L1109

https://github.com/bodleian/medieval-mss/blob/master/processing/convert2HTML.xsl#L1133-L1137

**Comment by ahankinson** [comment]
It seems that `bibl@facs` contains a lot of links to GIF files. I'm not sure that this is very useful...

**Comment by ahankinson** [comment]
I think this is fixed, but there is a separate issue with this which I will raise in a new ticket.
