### ISSUE TITLE
implement releases

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#120]
## Detailed Description
As suggested by @andrew-morrison in https://github.com/bodleian/medieval-mss/issues/22

## Possible Implementation
- add relevant text to About page, linking to https://github.com/bodleian/medieval-mss/releases
- tag the relevant commits https://git-scm.com/book/en/v2/Git-Basics-Tagging 
- create a changelog? (where?)

**Comment by andrew-morrison** [comment]
You can create releases on GitHub via a form:

https://github.com/bodleian/medieval-mss/releases/new

I assume anything you enter in the "Describe this release" box would be displayed somewhere on GitHub, effectively creating a changelog page.

**Comment by andrew-morrison** [comment]
13 backdated releases have been created, tagged to commits which @holfordm has identified as important additions, plus a couple I've spotted:

https://github.com/bodleian/medieval-mss/releases

There is a link from the About page on the web site to that URL, so we now have an overview of the history of the catalogue, without having to manually maintain a web page.

The titles and descriptions of each release can be edited. And new ones created in the future using the "Draft a new release" button.

GitHub probably sent a email for every release created, so sorry for the spam.
