### ISSUE TITLE
Lat misc b 12 art 20

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#121]
Correct the entry for this work, which is no longer attributed to Clarius, and the relevant entry in works.xml

cf. http://www.persee.fr/doc/bec_0373-6237_1982_num_140_2_450272_t1_0260_0000_7

**Comment by holfordm** [comment]
fixed via 3d0bf7a5b7b4b5cf8f9fb276becb66f5886da15e

**Comment by andrew-morrison** [comment]
FYI, you can close issues by [including a reference to them in commit messages](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by holfordm** [comment]
Good to know - thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
