### ISSUE TITLE
Improve error logging in indexing scripts

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#124]
## Detailed Description
Currently the indexing process notes all `<persName>` without `@key`, throwing up a lot of errors in the log, but this includes the persons in `<respStmt>`, who don't have keys.

## Possible Implementation
Restrict logging of `<persName>` without `@key` to descendants of `<msDesc>` to give a better picture of errors that need fixing.

**Comment by andrew-morrison** [comment]
Similar changes can be made to the scripts for works, places and organizations too. 

Also, as noted in #133, manuscripts.xquery could check for duplicate values in `/TEI/@xml:id`. It might add a few seconds, maybe half a minute on a slow machine. But it would be important for when multiple people could be creating new manuscripts descriptions at roughly the same time (as will be the case with Fihrist, especially.)
