### ISSUE TITLE
empty author elements cause display problems

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#125]
surplus commas, as here, item 10
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_940

## Possible Implementation
remove the empty elements as they should no longer be necessary now that the works are indexed

**Comment by andrew-morrison** [comment]
FYI, There are 170 self-closing `author` or `persName` elements with keys in Medieval. There are 26 in Fihrist. None in any other catalogues.

I could easily change the XSL to not insert commas when the `author` element is self-closing.

**Comment by andrew-morrison** [comment]
I guess it depends whether these self-closing elements are a mistake or intended to make explicit the relationship between the `msItem` and the `author` (which might be inferred from their being children of a parent `msItem` with the same author.)

If it is the former, then Oxygen's find/replace in files would be even quicker:

![image](https://user-images.githubusercontent.com/33721187/37356961-17548b28-26df-11e8-99d3-2c967c26f067.png)
