### ISSUE TITLE
Record for MS. Add. C. 87*

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#131]
There is a record for MS Add. C. 87, but part of it has been rebound as MS. Add C. 87*, which does not have a catalogue record. 

See: https://www.diamm.ac.uk/sources/484/

**Comment by holfordm** [comment]
This is already updated on QA - I spotted it the other day when going through DIAMM to add links from our records http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_10008

**Comment by ahankinson** [comment]
Ha. I've just been going through DIAMM, adding links to the Medieval Catalogue. 😄

**Comment by holfordm** [comment]
Great minds...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
