### ISSUE TITLE
"See also" links on work/person/place pages

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#132]
@holfordm: This is something I've identified a need for in other catalogues, but it might be most useful in Medieval, so I'd like to get your opinion on it.

Because the local authority files are expressed in TEI, it is possible to make use of generic TEI attributes such as `@corresp` or `@sameAs`. These can easily be picked up by the indexer, to create "See also" links. 

For example, the same work in different languages could be associated with each other using  `@sameAs`. Or those "pseudo-" people (as I understanding it those are used when works have traditionally been falsely attributed to someone whose philosophy or teaching were their inspiration), could be linked together with `@corresp`. Or, obviously, cities could be linked to regions, and regions to countries. It would have to be used fairly sparingly, otherwise maintaining the authority files could get messy, but I imagine it could be useful.

I've set this up for Senmai, which contains several examples of works split across multiple manuscripts. They could be merged into a single entry in the works index, but subject matter experts may expect to see them listed separately in the search results. So using `@corresp` to link each to all the others...

```
<bibl xml:id="work_1299" corresp="#work_99 #work_5 #work_1463">
...
<bibl xml:id="work_99" corresp="#work_1299 #work_5 #work_1463">
...
<bibl xml:id="work_5" corresp="#work_99 #work_1299 #work_1463">
...
<bibl xml:id="work_1463" corresp="#work_99 #work_5 #work_1299">
```
...means each gets links to the others on the web site, as shown here...

http://senmai-qa.bodleian.ox.ac.uk/catalog/work_99

Do you think this is useful, practical, and a valid use of these TEI attributes?

This relates to #34.

**Comment by holfordm** [comment]
This seems like a useful and valid approach to me. I can think of several medieval examples such as the different "decades" of Livy, books of the bible, etc etc. 
Would you create a schematron rule to ensure that all the `@corresp` matched up?
Is it something that would be done manually or automated? 
If it was done manually, it _might_ be worth thinking whether it would be worth classifying different relationships in more detail - e.g. "is part of" would be a different relationship from "is translated from". This might be done in `<listRelation>` [cf. this syriaca record for a work: http://syriaca.org/work/694/tei ]

**Comment by andrew-morrison** [comment]
Adding the attributes would be a manual step. Oxygen helps, a bit, with an auto-complete drop-down, but there are so many entries in each authority file that that it is of limited assistance.

`listRelation` is more powerful and expressive, but much more complicated, both to implement and to explain to people. It is something you'd have to add alongside the entries, or at the end of the list, rather than just an add-on.

A schematron rule is a good idea. I've created one in Senmai.

Do you want me to copy the necessary changes to Medieval (after I deploy to production this afternoon, so you can try it on QA?)
