### ISSUE TITLE
Duplicate manuscript xml:id

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#133]
Just noticed that there are two TEI files with the same `@xml:id` of "manuscript_9500":

- Christ_Church/Christ_Church_MS_688.xml
- Sparrow/MS_Sparrow_1.xml

Only the first one is displayed on the web site at https://medieval.bodleian.ox.ac.uk/catalog/manuscript_9500 because it happens to be the second one processed by the indexer, so it overwrites the first. I'm surprised Solr didn't throw an error when indexing.

The only way users might spot this is if they follow a link such as the one fourth from bottom here:

https://medieval.bodleian.ox.ac.uk/catalog/place_1000080

**Comment by holfordm** [comment]
fixed via 88c8f9daa313cf68eb1d2f58cb500eee928930a5
thanks for spotting this. I do an occasional check for duplicate ids but obviously missed this. If a check could be built into the indexing script, that would be very helpful.
