### ISSUE TITLE
new filter: digitized manuscripts

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#147]
Add a filter for manuscripts that have been digitized, either at Digital.Bodleian or elsewhere.
If desirable, distinguished between full digitizations and partial digitizations (where only a section of the MS. has been reproduced). When LUNA images go into Digital.Bodleian, there will also need to be a category like "sample images only".

## Context
Useful to users wanting to know what they can see online. Additionally, for medieval mss., the TEI catalogue currently provides a better search interface than Digital.Bodleian

## Possible Implementation
References to digitial reproductions take this form:
` <surrogates>
                     <bibl type="digital-facsimile" subtype="full">
                        <ref target="https://digital.bodleian.ox.ac.uk/inquire/p/b6391fb2-a52e-4c69-bc13-02c04a9256a7">
                           <title>Digital Bodleian</title><note>(full digital facsimile)</note>
                        </ref>
                     </bibl>
                  </surrogates>`
the values of `@subtype' should be "full" or "partial" reflecting whether the MS. is fully or partly digitized. Currently there are no references to reproductions of only a few images.

**Comment by andrew-morrison** [comment]
Sounds like a good idea and should be easy to implement.

But why would someone want to filter out (or narrow to) manuscripts that are only partially digitized? There's still a chance they will be able to see what they want to see, and there's no way for them to tell from just a label of "partial" while searching.

Currently there are 376 instances of `//surrogates//bibl/@subtype`, 4 of which are "partial" and the rest "full".

**Comment by ahankinson** [comment]
FYI, Luna is probably going to disappear this summer, and all content will be migrated to Digital Bodleian.

We're working on making sure the Luna URLs will resolve to the copies that will be in Digital Bodleian, but it's probably best to hold off making any new links to content in Luna.

**Comment by holfordm** [comment]
No links to LUNA content planned until it migrates to D.B.

The full / partial thing is maybe not an issue now, but when the LUNA content goes in, I think people will definitely want to distinguish between a digitized ms where they can see the whole thing, and one where there are only a couple of images.

**Comment by ahankinson** [comment]
OK -- we're looking into adding that.

**Comment by andrew-morrison** [comment]
I've set this up on QA:

http://medieval-qa.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=manuscript

Also manuscripts linked from works/persons/places/organizations pages get flagged if digitized, for example:

http://medieval-qa.bodleian.ox.ac.uk/catalog/work_4224
http://medieval-qa.bodleian.ox.ac.uk/catalog/org_8
http://medieval-qa.bodleian.ox.ac.uk/catalog/person_88956220

Alternatively I could list the digitized ones first, with a different label, then the rest.

BTW, there are quite a lot of `@type` values which are "digital-fascimile" instead of "digital-facsimile", but the indexing scripts look for both.

**Comment by ahankinson** [comment]
"Viewable online" seems a bit misleading; Would 'Digital images' be better? Or 'Digital facsimile'?

**Comment by andrew-morrison** [comment]
My thinking was "Viewable online" was less ambiguous than "Digitized", because something can be digitized but still only available in reading rooms (maybe not here, and not for manuscripts, but it still happens.)

**Comment by ahankinson** [comment]
@holfordm do you have an opinion?

**Comment by holfordm** [comment]
"Digital images online"? I'll ask Martin for his opinion as well.

**Comment by andrew-morrison** [comment]
I've updated the QA site.

**Comment by holfordm** [comment]
Martin and I have decided on "Digital fascimile online" for the moment. 
This should change to "Digital images online" when  the LUNA images are imported into DB and referenced from the catalogue. 
@holfordm should add something to the about or help page to explain exactly what the filter includes, cf. #101

**Comment by ahankinson** [comment]
The LUNA migration is imminent (we're currently hoping for sometime in August). Is there a reason why the wording changes after the Luna migration?

**Comment by holfordm** [comment]
The thinking was: "facsimile" implies images of a whole ms (or at least a whole section of a ms). "images" implies something broader. To have "images" without the LUNA images present and linked might be misleading (this was Martin's concern anyway)

**Comment by holfordm** [comment]
Change to repository - makes excellent sense. Thanks for spotting.
