### ISSUE TITLE
display and index former shelfmarks

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#156]
This issue arises particularly with the Merton manuscripts, where in addition to the modern number (MS. 1 etc.) there is an older number (A. 2. 1 etc.) which the college would like to be displayed and also to figure in search results. The old shelfmarks are marked up as follows:

<altIdentifier type="former">
                     <idno>A. 2. 1</idno>
                  </altIdentifier>

**Comment by andrew-morrison** [comment]
The lack of indexing is the same issue as #155.

The lack of display should be easy to fix. Do you want to displayed like [summary catalogue numbers](https://medieval.bodleian.ox.ac.uk/catalog/manuscript_48) but with a different label, e.g.:

> Former shelfmark: A. 2. 1

?

**Comment by holfordm** [comment]
Re display: that would be great.

I’m not sure that I’ve understand regarding the shelfmark indexing but we discuss it when we next meet in person perhaps.

________________________________
