### ISSUE TITLE
index variant titles in works

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#157]
It would be useful if variant titles (`title type='variant'`)in works.xml could be indexed. Most works don't have an extensive list of variants, but I'm adding them steadily, and variant titles are just as much a problem for discovery as variant name spellings!

**Comment by andrew-morrison** [comment]
They will be soon. The new versions of the indexing scripts I've been working on in the "processing-overhaul" branch, to fix several existing issues, already do: everything that isn't of `@type` "uniform" (or "display" for people and places) will be indexed as a variant. They won't be displayed (and therefore Google won't pick up on them.) I just need to find time to finish off my changes.
