### ISSUE TITLE
dimensions may include depth

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#159]
We will be creating records from the recent catalogue of Wuerzburg manuscripts for an upcoming project, and these records include depth as well as height and width in measurements. (Sample record: http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_7675).

The XSLT that generates the HTML should be adjusted to take account of `<depth>` if present: if present, to generate additional ×, and to put 'mm.' after `<depth>` rather than `<width>`

**Comment by andrew-morrison** [comment]
That shouldn't be difficult. I'll do it after I've finished the various indexing improvements I'm working on.
