### ISSUE TITLE
visual divisions between manuscript parts could be clearer

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#166]
In multipart manuscripts (e.g. https://medieval.bodleian.ox.ac.uk/catalog/manuscript_4820), divisions between the different parts are not very clear. It would be good to have, after `msPart`, a line, similar to that which now appears after `msItem`, or even a stronger visual signal.
I think this is also an issue in other catalogues with multipart manuscripts, e.g. Genizah

**Comment by andrew-morrison** [comment]
Parts are converted into div elements of class "msPart" in the HTML, so presumably this could be achieved with CSS to give them a border-bottom, as is currently done for .msItem

This would indeed be good for other catalogues. Genizah is the other big one for multi-part manuscripts, but Hebrew and Fihrist also have some, and in the latter they use all kinds of labels for their parts (for example, [just single letters of the alphabet](https://www.fihrist.org.uk/catalog/manuscript_3347) or [classmarks](https://www.fihrist.org.uk/catalog/manuscript_2111)).

**Comment by IgnatG** [comment]
//done-- it needs updating on QA

**Comment by andrew-morrison** [comment]
QA is now updated.

@holfordm: Take a look and let us know if you want a darker or thicker line between parts.

FYI, another small change I've recently made is to index the summaries displayed on the manuscripts search results. So on QA you can find examples by doing a search for "composite manuscript" and it'll list everything with an `msPart` that doesn't have an `msDesc/head`.
