### ISSUE TITLE
MSS Barocci 239a-b links to Digital Bodleian

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#168]
The links to Digital Bodleian in MSS Barocci 239a-b do not display correctly, and should probably be formatted into a list.

http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_920

**Comment by holfordm** [comment]
Digby 23 has the same problem, and there may be other examples.

The obvious solution is, in cases where `<surrogate>` contains more than one `<bibl>`, to wrap them in a `<listBibl>`, but at the moment that seems to cause problems with the display (at least, the Digital images field doesn't appear any more in the preview generated with previewmanuscript.xml).

Paging @andrew-morrison

**Comment by andrew-morrison** [comment]
The handling of `bibl` and `listBibl` needs to be reviewed in the XSL. I've created a new issue for that.

Meanwhile, I've put in workaround for these surrogate links so if there is more than one they'll each display on a newline. It's in the consolidated-tei-schema repository so will work whatever branch of medieval-mss you are on.
