### ISSUE TITLE
Zotero bibliography in MSS only

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#17]
references and links to the Zotero bibliography do not need to appear on Person or Place pages, just on Manuscript pages.

**Comment by IgnatG** [comment]
Could you take a screenshot of this on the current website, please? - you can drag an image here to upload it.

I'm asking this because we thought this is already fixed .

**Comment by ahankinson** [comment]
I'm surprised as well, because I'm pretty sure I fixed it this weekend.

**Comment by holfordm** [comment]
Looks like I raised the issue without checking the most recent version of the site, sorry.
