### ISSUE TITLE
health warnings on index pages

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#172]
Due to the nature of the catalogue, which contains a lot of summary records with incomplete descriptions, there is a case for providing warnings on the index pages for persons, works and places. 
They might appear after any external links and might say something like "the following references reflect [the current coverage of the catalogue] and are unlikely to be comprehensive". The part in square brackets could link elsewhere (e.g. a more developed version of this page, https://github.com/bodleian/medieval-mss/wiki/The-catalogue-records:-sources,-coverage-and-scope)

- is this a good idea?
- would it be easy to implement technically?

**Comment by andrew-morrison** [comment]
Inserting such messages in the middle of the list of fields would be technically difficult. More likely to be possible is a paragraph at the bottom, after all the links. Possibly in a form of a footnote as in this mockup:
![mockup_of_footnote_on_person_page](https://user-images.githubusercontent.com/33721187/43534024-3c689cae-95ae-11e8-9ca4-85137b4a91a0.png)

**Comment by ahankinson** [comment]
I should rephrase: What level of comprehensiveness would our users expect? Is it better to provide this notice on person/place/work, or to have a note on the MS record that indicates the level at which the MS is described?

It just seems like we're being a bit oblique with our language here -- What is meant is 'Not all of our records are fully described, and as such this is not a comprehensive list of all occurrences of this person in our collection.' 

It seems to me that that sort of general note can be made at a higher level (under 'About', possibly) than on every individual person/work/place record?

**Comment by andrew-morrison** [comment]
@holfordm can answer this better, but there are some examples in recent comments added to #79

**Comment by holfordm** [comment]
The about page does, I think, already cover this question quite well, but my worry is that no-one reads the about page, and there may be an expectation from users that the page for Cicero's Orationes in C. Verrem for example (http://medieval-qa.bodleian.ox.ac.uk/catalog/work_1259) contains all known copies of that text in the Bodleian, which it doesn't, because some are hidden in the record for Cicero, Works (http://medieval-qa.bodleian.ox.ac.uk/catalog/work_1276)
On the one hand we don't want the records to look overly fussy, on the other hand we don't want to mislead users.

**Comment by holfordm** [comment]
Martin Kauffmann agrees about the need for warnings. The form of words should be "The above references reflect only [the current coverage of the online catalogue] and may not be comprehensive.".

The link should be to the About page in the first instance.

**Comment by andrew-morrison** [comment]
Just to confirm, these should be on work, person and place pages? Not manuscripts or search results.

**Comment by ahankinson** [comment]
OK. 

Should we do this same warning for the other TEI Catalogues?

**Comment by holfordm** [comment]
Probably not necessary on search results since they will lead to manuscript or index pages. On manuscript pages with a summary description we might clarify what that means perhaps, but that would be a data change in the TEI.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by IgnatG** [comment]
this is done now
