### ISSUE TITLE
links to Zotero not working for MSS. D'Orville

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#174]
On this page, for example, http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_4155, the link generated is to "https://www.zotero.org/bodleianwmss/items/tag/MS.%20D".

Presumably this is something to do with the apostrophe in "MS. D'Orville" needing to be escaped

At present I think this collection is the only one whose shelfmark contains an apostrophe. 
Are there any other characters that could cause problems in the future?

**Comment by IgnatG** [comment]
the apostrophe should be the only one as it stops the URL from formatting too early. 
I'll investigate

**Comment by IgnatG** [comment]
this should be fixed now. It needs updating on QA at first. @andrew-morrison can you do this, please?
@holfordm can you check after if everything is ok? close the issue if it's all good. Otherwise, let me know and I'll investigate

**Comment by holfordm** [comment]
Yes, this is working now. close when prd updated?

**Comment by andrew-morrison** [comment]
Fixed on production.
