### ISSUE TITLE
variations in font size

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#175]
There are (since the processing overhaul, I think), some variations in font size on the QA site that seem a little random. This page http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_6752 is quite a good example. Any thoughts @andrew-morrison  or @IgnatG  ?

**Comment by IgnatG** [comment]
This one is for me. The problem was that some tags have a smaller font size. But now I've changed it so that all of them look the same. I'll close the issue once it goes on QA

**Comment by andrew-morrison** [comment]
What specifically in that page? It might be more obvious with your combination of computer, browser and settings.

**Comment by IgnatG** [comment]
this should be fixed now. @holfordm can you double check, please?

**Comment by andrew-morrison** [comment]
The CSS changes seem to have expanded the size of the header on mobiles (at least according to Firefox's responsive design view. Of course, it isn't a fixed header, so you can scroll past it, but you have to do that every time you go to a new page. It does make the buttons easier to tap.

**Comment by IgnatG** [comment]
Yes. It used to be in a narrower - if that's a word, container on mobile. The screen was already small so there was no need for that

**Comment by andrew-morrison** [comment]
Some of the recent CSS changes has removed bullet points, which are used especially on work/person/place/subject pages, on all catalogues on QA.

**Comment by IgnatG** [comment]
can I get an example of where this happened?

**Comment by andrew-morrison** [comment]
Any work or person or place page, e.g.: http://medieval-qa.bodleian.ox.ac.uk/catalog/place_7011931

**Comment by ahankinson** [comment]
Closing as this seems to be fixed now.
