### ISSUE TITLE
MSS. Arch. Selden.

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#18]
should have a period after the Selden - and perhaps merge A and B into a single collection

**Comment by holfordm** [comment]
@IgnatG I have merged Selden_A and Selden_B into a new collection, Arch_Selden - the xml should be up to date, is there you need to do in blacklight to update the collections lists?

**Comment by IgnatG** [comment]
I think it needs a pull now to be able to see it on the webpage. I can do it on my local machine but I don't have access to black01 server. That's @ahankinson playground. :)

**Comment by ahankinson** [comment]
Yes; I can't do a site update because the wifi at the conference doesn't let me get on the Oxford VPN, so this will have to wait.
