### ISSUE TITLE
change to convert2HTML xslt?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#183]
I think there has been a change to this script which affects the order in which some elements are displayed when the `msItem` element is nested. Specifically it seems that the language and notes elements of the main msItem now display before any nested items, regardless of the order in the xml. The result is that a note that is intended to appear at the end of a record can now appear in the wrong place, as in this record, http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_2176, where the sentence beginning 'de babilonia' should ideally appear before the dotted line preceding '(fols. 106v-107r)'
- was this an intentional change? - if there is a good reason for it, the TEI can be adjusted to display correctly

**Comment by andrew-morrison** [comment]
Yes, sorry, I changed this about a month ago, to deal with other catalogues which have some random ordering of child elements within msItems (e.g. Senmai, which was exported from a database used by their old web interface.)

I thought I had tested it by diff'ing the processing/html folder before and after the change but I must have missed out Medieval, or not noticed the effect it had. Doing so now I can see it affects 372 files, to one degree or another. Most of the time it just moves the Language(s) field up, but that can then cause problems when a note has been written to give context to the sub-items, as in this example:

https://medieval.bodleian.ox.ac.uk/catalog/manuscript_8525
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_8525

So now I've made it customizable for each catalogue and set up Medieval with an override to put it back the way it was, so everything should display in the order in the source TEI. I've re-indexed QA, but I'll left it for you to do so for production.
