### ISSUE TITLE
MSS. Latin on home page

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#19]
The collections MSS. Lat. misc. and MSS. Laud. Lat. both appear just as "MSS. Latin" on the home page.

**Comment by IgnatG** [comment]
That's well spotted!
Normally the collections have some parenthesis as well but I removed them because they would occupy too much space on the buttons. 
-- Essentially I took what was inside the parenthesis out and put in on the webpage. 
I will fix this though.

**Comment by IgnatG** [comment]
This has been fixed now and it will be reflected on black01 server when Andrew is back.
