### ISSUE TITLE
Adding digital surrogate IDs to records

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#195]
This is a proposal to add Digital Bodleian IDs to TEI files. I propose the following structure:

```
<altIdentifier>
    <idno type="URI" subtype="digital-surrogate">urn:uuid:ae9f6cca-ae5c-4149-8fe4-95e6eca1f73c</idno>
</altIdentifier>
```

This can be added at both the top Manuscript level, or at the individual part level (msPart) as necessary.

If this is accepted, I will file a second practical issue for converting existing Digital Bodleian URLs to `idno`s.

**Comment by holfordm** [comment]
should the `@type` of `<idno>` be more specific (e.g. digital-bodleian), since there may be digital surrogates of an item at other institutions?

**Comment by schassan** [comment]
Just as an idea: We have one TEI-file representing **the manuscript** and arbitrarily many other files, each representing one catalogue description for that respective manuscript. In the TEI file for the manuscript we store the digitisation information in `<publicationStmt>` respectively `<pubPlace>`:

```
<pubPlace>
   <ptr type="purl" target="anyURI"/>
   <ptr type="thumbnailForPresentations" target="anyImageURI"/>
</pubPlace>
<idno type="URN">anyURN<idno>
```

see also this example: [http://diglib.hab.de/?db=mss&list=ms&id=81-17-aug-2f&mode=xml](url)

**Comment by holfordm** [comment]
@andrew-morrison is this issue still live?

**Comment by andrew-morrison** [comment]
The Digital Bodleian IDs are inside the URLs in surrogates, so I don't think there's any need for this.
