### ISSUE TITLE
E-mail address in 'availability' is not clickable.

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#198]
In the restricted access notice the e-mail address for special collections enquiries is not a clickable `mailto` address.

**Comment by holfordm** [comment]
how do we make it clickable? If I put the address in `email` tags, can the html transformation do the rest?

**Comment by ahankinson** [comment]
Yes, that would work.

**Comment by holfordm** [comment]
commit b3bff057dea227e5acaacb5f1645a96bff44b564 fixes the data, but I'll leave the issue open until the html transformation has been updated (assuming an update is necessary @andrew-morrison ?)

**Comment by andrew-morrison** [comment]
The XSL doesn't convert `email` TEI elements to HTML `a` tags. I don't believe it has been requested until now. There might be some arguments for directing people to the contact form instead (mailto links only works if you're on your own computer or logged in to your own account on some university system) but I'll make the changes this week or next.
