### ISSUE TITLE
adding Jesus College manuscripts

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#199]
The librarian of Jesus College would like to add short descriptions of their manuscripts to the online catalogue. The information has been provided in a spreadsheet:
[Copy of Coxe's catalogue entries for Jesus - decoration and origin added.xlsx](https://github.com/bodleian/medieval-mss/files/2699072/Copy.of.Coxe.s.catalogue.entries.for.Jesus.-.decoration.and.origin.added.xlsx)

I can use this myself to generate the TEI records, but I wondered if we should maintain a script in one of the repositories for conversion of this or similar data (together with guidelines on how to structure the data), as it seems likely the situation will arise with other institutions.

The librarian wants to accompany the descriptions with images from the printed catalogue. Sample: 
![ms 001](https://user-images.githubusercontent.com/20242772/50288460-e6133980-045d-11e9-8b95-b21d369fda3b.png)
Presumably we would be able to put these on the server alongside our Summary and Quarto catalogue images?

**Comment by andrew-morrison** [comment]
I can write a script to convert each row in the spreadsheet into a TEI document. I've done similar before (e.g. to convert spreadsheets into EAD for modern archives.)

@holfordm: If you can do one manually, I'll use that as a template.

The script can be kept, and adapted in the future for other colleges or similar uses. As long as the spreadsheets are roughly similar, it won't be a problem, and easier than defining things rigidly now. One thing that does need to be standardized is how multiple values are encoded in one cell. In the Jesus one both pipe symbols and semicolons have been used.

The printed catalogue images can be added. Are there ~150 of them, one for each row in the spreadsheet? They can be sent by zipping them up and uploading to https://oxfile.ox.ac.uk

**Comment by holfordm** [comment]
There is a sample file in a new `Jesus_College` directory in `collections` (http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_10450). The identifiers for Jesus College will run from 10450.

Here is a revised copy of the spreadsheet.
[Coxe-rev.xlsx](https://github.com/bodleian/medieval-mss/files/2768989/Coxe-rev.xlsx)

Conventions are:
- the pipe | separates the different sections of a multi-part manuscript
- in column B, a comma separates author and title (except in MSS. 71-3), and a semicolon separates different msItems
- in column C a semicolon separates different languages

I'm anticipating that any key attributes on authors and titles will need to be added manually but hoping that the dating, language and other attributes can be added by the script.

**Comment by andrew-morrison** [comment]
OK, those conventions make sense.

As for attributes:

- For dates, I take it from your sample that "late" approximates to the last decade of the century, and "early" is the first decade
- For languages, ISO 639-1 should cover it
- I'll add n and xml:id attributes by sequence (resetting for each part)
- Looking up authors and titles against the authority files is unlikely to match anything, unless I make it so fuzzy that it'll create false positives. But places of origin should be easy to match against places.xml

I should be able to find time to do this next week.

**Comment by andrew-morrison** [comment]
There are some problems with column B. When there are no commas, semicolons or pipes, it is presumably a single work, but does the cell contains the title or the author? Also, is the following three works, or one title authored by two people?
```
Anselm; Boethius; mathematical extracts
```

**Comment by holfordm** [comment]
In some cases items with no comma (etc) are titles (e.g. MS. 5), in some cases authors (e.g. MS. 34). Best to treat them all as titles in the conversion and tidy them up later. In the above example there are three works: 
`<msItem><author>Anselm</author></msItem>
<msItem><author>Boethius</author></msItem>
<msItem><title>Mathematical extracts</title></msItem>`

**Comment by holfordm** [comment]
re. your earlier comment - yes, early = e.g. 1400-1410 and late = e.g. 1490-1500.

**Comment by andrew-morrison** [comment]
BTW, I've noticed that Hereford/Herefordshire is listed in places.xml as a country (in its type attribute). That is why it appears in the Origin filter, whereas Gloucester/Gloucestershire does not, because my script has tagged it with the `country` TEI element in a couple of these new records.

**Comment by andrew-morrison** [comment]
Sorry, I've realized I mistakenly started the Jesus manuscript IDs at 10550 instead of 10450. But I assume a 100-record gap is better than regenerating them and re-applying manual fixes.

Otherwise, as Owen seems happy, can we close this issue?

**Comment by holfordm** [comment]
No problem.

I'll close when PRD is reindexed which I hope to do today or tomorrow.

**Comment by ahankinson** [comment]
I'm guessing this can be closed now?
