### ISSUE TITLE
attributes lost on name[type='corporate']

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#2]
`name type="corporate"` has lost other attributes (e.g.` @ref, @key, @role`) on conversion to orgName. Example: Bodley_0065 at `<origPlace>`.

**Comment by jamescummings** [comment]
Yeah, same problem as the persName issue, with the same question. I'll treat them alike.

**Comment by jamescummings** [comment]
Ok, this is done in my script.  I notice a related issue where there are lots of `<persName>` inside `<name type="corporate">`.  I've not found one yet that I would call a person.  Am I right that these should just disappear?  
i.e.

````
<name type="corporate" role="formerOwner"><persName>Merton College</persName></name>
````
become
````
<orgName role="formerOwner">Merton College</name>
````

**Comment by holfordm** [comment]
yes, that is right.


<persName> inside <name[type=person] and type=corporate]> and inside <author> is a hangover from Fihrist / cambridge practice.


________________________________

**Comment by jamescummings** [comment]
Should I be getting rid of persName inside author? Most of the time there is only a persName (if there is one) in 7 cases it is also got another element there (often title.... which seems weird to me) i.e.

````
<author ref="http://viaf.org/viaf/99942145">
       <persName>Livy</persName>
       <title>Ab urbe condita</title>
 </author>
````
Should I try to move title outside of author? i.e.

````
<author ref="http://viaf.org/viaf/99942145">Livy</author>
<title>Ab urbe condita</title>
````

**Comment by holfordm** [comment]
those 7 cases look like errors - can you send me a list, I'll fix them.


after that, yes, persName inside author can go.


________________________________

**Comment by jamescummings** [comment]
Easy enough to add to the conversion a rule for author elements that have a title that moves it outside, and a rule for title elements inside author elements that makes them (otherwise) vanish.  So no worries... just wanted to check it was the right thing to do.

**Comment by holfordm** [comment]
Might be worth me double checking in case there are other elements in there as well? e.g. note?

**Comment by jamescummings** [comment]
Notes inside author don't really bother me.... but titles inside author are just nonsensical in my opinion. So I'm running the conversion again with that updated and hopefully the persName and orgName things straightened out.

**Comment by holfordm** [comment]
I agree. It's just an error where the author tag has got wrapped around more than it should have.


________________________________

**Comment by jamescummings** [comment]
I believe this is done, so I'm closing it. re-open if it is still a problem.
