### ISSUE TITLE
html representation of `formula` element

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#203]
This element seems to appear as a `div` at the moment. This isn't usually a problem but there are some descriptions where continuous text is assumed, and `span` would be preferable - for example https://medieval.bodleian.ox.ac.uk/catalog/manuscript_4452, collation section. 
Can we change its treatment (at least in medieval) to always render as `span`? I don't think this will have any undesirable consequences.

**Comment by andrew-morrison** [comment]
I've made the change and re-indexed QA. It affects seven records:

http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_8834
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_343
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_1378
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_1591
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_4452
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_4468
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_8960

Take a look, and if you think it should be a `div` in some contexts and a `span` in others then that can be done.

The `formula` element has been used quite a lot in Fihirst. Currently this is a Medieval-only XSL customization, but when I get a chance I'll test what the effect would be on Fihrist if it was applied universally.

**Comment by holfordm** [comment]
Looks good for medieval
