### ISSUE TITLE
attribute of `term` should not display in medieval catalogue

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#204]
If I have this TEI
`Punctuation by <term type="punctuation">point</term> and <term type="punctuation">double point</term>`
It will currently display as:
Punctuation by punctuationpoint and punctuationdouble point.

which is not desirable! I've reviewed the use of the `term` element in the medieval catalogue, and it isn't currently used (so this won't affect any records), but I've recommended its use in various contexts of the Guidelines. 
presumably, though, there are contexts in other catalogues where the display of the attribute is desirable?

**Comment by andrew-morrison** [comment]
That's just the default that the XSL is set up to output when there is no specific template.

The `term` element is used in keyword lists in other catalogues, but not in `sourceDesc`.

How should your example be displayed? Just the text? Rendering the terms in bold or italic? With the type attributes displayed as tooltips when hovered over with a mouse?

**Comment by holfordm** [comment]
Fine to display just the text - thanks
