### ISSUE TITLE
bibl@facs should contain absolute URLs

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#21]
Currently bibl@facs elements contain just a relative URL (e.g., `aam0096.gif`) with no indication of where to find this image. This means that the actual URL must be added to the record in the processing stage. This should be stored in the record itself.

So `bibl@facs` should be expanded to contain the full URL so that these records are more portable.

**Comment by ahankinson** [comment]
As a side note, these images should also be moved from tolkien-prd since that machine will be decommissioned after the new site goes live.

**Comment by holfordm** [comment]
@ahankinson  if you provide me with the full URL I can easily make this change. It would be slightly easier if all the gifs were in a single folder (rather than separate directories for each catalogue as currently), how would you feel about that?

**Comment by ahankinson** [comment]
How many images are we talking about? If it's over a few hundred I would keep them in separate folders.

**Comment by holfordm** [comment]
There are a lot; so separate folders it is.
How about something on these lines: medieval.bodleian.ox.ac.uk/images/aaq/aaq0324.gif
Will it be http or https?

**Comment by ahankinson** [comment]
https.

I was thinking of checking them into this git repo so that we can automatically deploy them to a server if we need to, and so they don't get lost on a server. Would this be OK?

**Comment by andrew-morrison** [comment]
Can this issue be closed? Now the images are on the same server, they don't need absolute URLs. But they're not checked in to this repository. Is that still desirable/practical?
