### ISSUE TITLE
Improve formatting for digital surrogates

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#211]
Formatting and linking for digital surrogates is currently inconsistent. Some links include the 'note' field, while others don't, e.g., 

```
<ref><title></title><note></note></ref>
```

and

```
<ref><title></title></ref><note></note>
```

A minor style issue, but probably something where we can decide on a style and then fix whenever we see it.

**Comment by holfordm** [comment]
Most examples are of type 1, which also looks better when displayed (I think), so I say we go with that.
