### ISSUE TITLE
Print Stylesheet

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#23]
Currently the default print styles look pretty awful. We should have a print stylesheet that lets people print off a well-formatted version of a record, as well as a page of search results.

**Comment by holfordm** [comment]
If possible, ability to export search results (eg. to csv) would also be useful.

**Comment by ahankinson** [comment]
Export to CSV will likely not happen, since this will require additional Blacklight development.

**Comment by IgnatG** [comment]
done: print style added for individual records and search results
