### ISSUE TITLE
Add unique identifiers to works

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#24]
Currently a work record (in `works.xml` does not contain a unique identifier (e.g., `work_1234`). For indexing works it is required that we're able to match that with a reference in each MSS with a unique identifier.

**Comment by holfordm** [comment]
On it - I need to do another check for duplicates before I add the identifiers, then I will link them to the descriptions with `@key="work_xxxx"` on `msItem` - this should be early next week.

**Comment by ahankinson** [comment]
👍 We'll keep this open so you can let me know when this is done.

**Comment by holfordm** [comment]
A large proportion of works (currently those without authors) now have unique identifiers [`@key` on `msItem/title`] which link to the `xml:ids` in works.xml.
I will add the other links (works with authors) early next week.

**Comment by holfordm** [comment]
This should all be in place now. Cf. issue [37](https://github.com/bodleian/medieval-mss/issues/37)

**Comment by holfordm** [comment]
closed
