### ISSUE TITLE
Fix typo in TEI records

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#240]
A number of records contain a typo in the `@type` attribute for 'digital-facsimile'. See discussion here: https://github.com/bodleian/medieval-mss/pull/237#discussion_r295729757

We can automatically correct this with find/replace, but it will involve updating all of these records across the catalogue.

@holfordm thoughts?

**Comment by holfordm** [comment]
fixed by 3355fe4869c92eef60bd78d23b8a9be94a8a5e99
