### ISSUE TITLE
indexing absence of decoration

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#248]
In some descriptions the absence of decoration is explicitly indicated, 
`<decoDesc>
                        <decoNote>None.</decoNote>
                     </decoDesc>`

Currently, I suspect that because in these descriptions the `decoNote` element is present, they are being indexed as containing decoration.
I suggest that in these cases the `decoNote` be given a type of `none` (several records already have this), and these can then be excluded from the decoration filter.

**Comment by andrew-morrison** [comment]
I've implemented a change to the indexing script to look for a type attribute of "none".

If you want to add those attributes to other files, it'll remove those manuscripts from the "Yes" option in the Decoration facet.

The following XPath can be used in Oxygen's Find/Replace in Files, to help find candidates: `//sourceDesc//decoDesc/decoNote[not(@type='none')]//text()`. As well as "None" there are some that contain "No decoration".
