### ISSUE TITLE
sorting oddities in indexes

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#28]
Persons

- ..., dom. William (under 'dom'; better at beginning or end?)

- Łaski, Jan, 1456-1531 (sorts under aski)

- Ǧābir Ibn-Aflaḥ, 1100-1160 (under bir)

- Władysław, III Warneńczyk, King of Poland and Hungary, 1424-1444 [out of sequence after Wa]

- Sánchez de Arévalo, Rodrigo, 1404-1470 [in sequence under sn]

- .... [various entries starting this way; possible to group all at beginning?]

**Comment by ahankinson** [comment]
I think this is now fixed on QA. Please check and re-open if it isn't.

**Comment by holfordm** [comment]
the ... entries were grouped at the beginning of the sequence yesterday (which is good), but today they seem to be back in alphabetical sequence e.g. ..... dom. William under D

**Comment by ahankinson** [comment]
Fixed now.
