### ISSUE TITLE
new URLs for Zotero bibliography

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#287]
To make collaboration with bibliographic records easier, we have converted the Bodleian's Zotero library into a group library. 
The existing URLs (in this form) still work

but future records will be added to the group library, with URLs in this form:
https://www.zotero.org/bodleianwmss/items/tag/MS.%20Bodl.%20779

https://www.zotero.org/groups/434020/bodleian_library_western_medieval_manuscripts_bibliography/items/tag/MS.%20Bodl.%20779 

Can we change the script in medieval.bodleian to search for and point to the latter URLs?

**Comment by andrew-morrison** [comment]
I've made this change on the QA server. Let me know if it is working how you expect, and I can deploy to production.

**Comment by holfordm** [comment]
Seems to be working perfectly - thank you

**Comment by holfordm** [comment]
Does the javascript that uses the Zotero API also need to be updated, so that the correct number of references appears at the bottom of the record? (https://medieval.bodleian.ox.ac.uk/catalog/manuscript_10157 says 6 records in Zotero but there are currently 15 for example)

**Comment by ahankinson** [comment]
Yes, the number is still being taken from the old list, not the new list.

**Comment by andrew-morrison** [comment]
@holfordm: Please test on QA. I'll deploy the change to PRD next Tuesday morning.

**Comment by andrew-morrison** [comment]
I have deployed this change to the production web site.
