### ISSUE TITLE
Make brackets part of rendering in <locus>

### ISSUE THREAD

**Issue by adunning** [bodleian/medieval-mss#292]
We are asking cataloguers to include backets when giving a reference in `<msItem>`, e.g. `<locus>(fols. 85r–120r)</locus>`. This is presentational, and it would improve consistency to make this part of the display rather than hardcoded.

**Comment by andrew-morrison** [comment]
Adding brackets in the XSLT is possible. The decision just needs to be made when to go ahead and search and replace all the hardcoded ones in the `locus` elements.

**Comment by holfordm** [comment]
Two questions - do we want this to apply (I think we do) only to locus when it is the first child of msItem? are there any possible problems in (for example) finding and replacing `<locus>(` with `<locus>`?
