### ISSUE TITLE
linking to abbreviations and editorial conventions

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#306]
Many catalogue entries include abbreviations which are not always obvious to users.

There is an incomplete list of these on the wiki (https://github.com/bodleian/medieval-mss/wiki/Abbreviations) (is this the best place for it? where else could it go?)

It would be useful to provide a link to this page (or another location if we decide on a better one) from the catalogue entries, perhaps at the bottom of the record. 

It would also be useful to link to a similar page (currently also incomplete...) about cataloguing conventions (https://github.com/bodleian/medieval-mss/wiki/Conventions)

**Comment by adunning** [comment]
Could we simply make `<abbr>` part of the rendering to provide an alternative? Presumably one could match strings from our list of known abbreviations, or use extra markup if that is felt to be too delicate.

**Comment by andrew-morrison** [comment]
The web site will display a "Key to Abbreviations" at then end, plus the expansion in a tooltip where it occurs in the description. You can see this working here:

* https://www.fihrist.org.uk/catalog/manuscript_13089
* https://github.com/fihristorg/fihrist-mss/blob/9323edbe18c32939a911dcf196f11da169f893e4/collections/wadham%20college%20(university%20of%20oxford)/WadhMinasian_19.xml#L82-L98

`abbr`, once defined by being inside a `choice` with a silbing `expan`, can be reused on their own elsewhere. But you have to redefine them in each TEI document they occur.

If, instead, you'd like the Medieval catalogue web site to link all `abbr` to your GitHub wiki page, that is a customization which could easily be set up. If you want to link each abbreviation to jump to the specific entry in the wiki page, you could add anchors into the wiki page then insert `ref` elements inside the `abbr`.

**Comment by adunning** [comment]
Brilliant – could we run a script now and again to add the relevant elements to the source file? It would a pain to have to type the `choice` structure at every instance.

**Comment by holfordm** [comment]
It's interesting to know that Fihrist is set up for this. It would be a lot of work to add the markup to existing files though. So I wonder if a simple link to the abbreviation list would be a better solution for now. And we need a link to the conventions in any case.

If we do include abbr tags going forward, is there a more efficient way than using the choice and expan tags (which seems to defeat the point of abbreviations in saving time!). Could we have a separate two file with the expansions?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andrew-morrison** [comment]
`abbr` is a core TEI element, so probably intended for transcriptions, where defining the expansion once for an abbreviation used multiple times in one document is a big saving.

It does have a `@source` attribute, which could point to an XML file in the same repository containing some kind of list structure within which all the `choice/abbr/expan` are contained, similar to the authority files. The indexer could look these up when building the HTML pages, and report a warning if it finds an abbreviation for which there is no expansion.

Or an XSLT script to add expansions from a predefined list would also be possible. But we'd have to train cataloguers how to run it. And if any of the expansions change in the future, it'd require searching and replacing existing instances.

Where would a link to the conventions wiki page go? In the about page? At the bottom of every record?

**Comment by holfordm** [comment]
might there be few enough abbreviations to include a document listing them as a variable in the schema, that would show any problem abbreviations as cataloguers worked?
There is still the issue of how to convert existing files - would it be realistic to do this with a script?
It would probably be best to link to conventions from the bottom of every record since people rarely read the about page.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by holfordm** [comment]
Would the abbreviations display before the Zotero link? Because I can imagine a long list would stop people finding that link.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andrew-morrison** [comment]
Schematron can lookup values in a separate XML fi8le, to decide which are valid in the file it is checking. It could do so for the authorities now, except it would make validating incredibly slow if it had to lookup every `@key` value against three large files. A dozen or so abbreviations in one small file might be less of an issue.

An XSLT script find and alter existing `abbr` tags would be easy to write. Or Oxygen's Find and Replace in Files could be used, with some regex. If the abbreviations are distinctive enough it would be possible to find instances which aren't currently marked up.

A key to abbreviations and/or links to GitHub wiki pages would have come before the Zotero link.

**Comment by andrew-morrison** [comment]
Here is what is currently marked up with `abbr` tags:
```
     74 Hutter
     11 AT
      3 BLR
      2 Griffiths FS
      1 P&amp;A
      1 Pächt &amp; Alexander
      1 NIMEV
      1 est
      1 DIMEV
      1 BHL
      1 AO<hi rend="italic">mod</hi>
```

**Comment by holfordm** [comment]
Yes - that's only a small number of actual abbreviations unfortunately. Things like PL, PG etc would have to be a find and replace in files job.
I think we would need to consider seriously the risk of the Zotero link being obscured.

**Comment by andrew-morrison** [comment]
I could make the **"N item(s) related to this MS. have been found in our bibliographical database"** sentence bold, if that would help.

**Comment by holfordm** [comment]
Pending further implementation of the Fihrist system (which requires a fair amount of work in the TEI, and work on the implementation), is it worth returning to the simpler fix of a link to the existing list of abbreviations and conventions? Could work on this be combined with #22 and #165?

**Comment by holfordm** [comment]
Flagging the possiblity of a simple link again as a temporary fix - could be good to implement before the start of term?

**Comment by andrew-morrison** [comment]
Something like this mockup (on every manuscript page or just the ones containing at least one `<abbr>`)?

![abbreviations_mockup](https://user-images.githubusercontent.com/33721187/94419420-a91fbf00-017a-11eb-81a5-029f58787b9e.jpg)

**Comment by holfordm** [comment]
Yes, exactly so - on every page (since `abbr` tags won't always be present yet even when they should be). Ideally we would have
"View [list of abbreviations] and [editiorial conventions]" with the latter linking to https://github.com/bodleian/medieval-mss/wiki/Conventions
