### ISSUE TITLE
Creating a public dataset

### ISSUE THREAD

**Issue by adunning** [bodleian/medieval-mss#309]
We had a request for a CSV version of our manuscripts list, and it strikes me that we could make a useful public dataset out of this. Any suggestions to improve on the following (thinking of what can export reliably and is fairly normalized)?

- Shelfmark
- SC number
- `msName`
- date (3–4 columns? for text, `notBefore`, `notAfter`, and any precise date given)
- place of origin (ID only? ID+text?)
- `head` or summary contents if unavailable (as generated online)
- languages (as ISO codes?)
- IDs + text for works in `msItem`
- IDs + names for former owners
- support material
- dimensions
- second folio
- `type`s from `decoNote`

@andrew-morrison has suggested creating a separate line for each part in the case of composite manuscripts.

**Comment by andrew-morrison** [comment]
A lot of the same fields (but not all) were [mapped to CIDOC-CRM and FRBRoo ontologies](https://github.com/mapping-manuscript-migrations/bodleian-mmm) and [exported as RDF](https://github.com/mapping-manuscript-migrations/bodleian-rdf) for the [Mapping Manuscript Migrations](https://mappingmanuscriptmigrations.org/) project. It would probably be possible to formulate a SPARQL query to run against their triple store, although the data is a snapshot from last year. I believe the idea is we'll eventually publish linked data of our own, updated regularly, which would cater for the more advanced researchers. But a simpler CSV export could also be useful for those who just want something they can copy and paste into a spreadsheet.

**Comment by tobyburrows** [comment]
The MMM project's RDF version of the Bodleian data can be downloaded from the Zenodo repository here: ([https://zenodo.org/record/3667486](url))
There's a separate Turtle file for the Bodleian data.
