### ISSUE TITLE
manuscript `origPlace` should be indexed by `@key` not by string value

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#31]
@holfordm to supply list of mappings between country value and key value

**Comment by ahankinson** [comment]
Reminder on this one...

**Comment by holfordm** [comment]
this should be a complete mapping of `country/@key` to the desired filter text

[country-code-map.txt](https://github.com/bodleian/medieval-mss/files/1135674/country-code-map.txt)

**Comment by ahankinson** [comment]
Fixed now.
