### ISSUE TITLE
MS Bodl 277

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#324]
Creating an issue for discussion first, rather than a pull request: There is another single image item for MS Bodl 277 listed in Digital Bodleian that is not in the TEI record:

https://iiif.bodleian.ox.ac.uk/iiif/viewer/81772d5f-704e-4d4c-a692-25f1c8799da0

Should this be added to the TEI record?

**Comment by holfordm** [comment]
Yes, I suppose as a separate digital bodleian record with a note that it includes only the woodcut?
