### ISSUE TITLE
place index should include organizations

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#33]
the authority file places.xml includes places and organizations, listPlace/place and listOrg/org. Both should be treated as place objects for the purpose of SOLR indexing and both will appear inthe place index. The orgs will have URLs in the form ..catalogue/org_xxxx.

**Comment by holfordm** [comment]
Sorry to reopen this but the place index now ONLY includes organizations!

**Comment by ahankinson** [comment]
That's not a problem with the indexing... I just didn't hit the right button.
