### ISSUE TITLE
person, work and place records should display links and additional info. where available

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#34]
in persons.xml the fields `note[not(@type)],` `bibl,` and` note[@type=links]` should display as part of the relevant person record, with live links. 
e.g. for person_147 the record might read 
Benedictus Bursa, fl. c. 1450
**Bibliography:** CALMA II.206
**Links:** Mirabile

**Comment by ahankinson** [comment]
Recall that for people we're not generating HTML, so including all of the information contained in these fields is difficult. I can, for example link something like this:

```
<ref target="http://www.treccani.it/enciclopedia/cristoforo-duodo_(Dizionario-Biografico)/">
     <title>DBI</title>
</ref>
```

It is more challenging, however, to link something like this:

```
<note>Perhaps to be identified with <ref target="#person_1001">William North, vicar of Saltby</ref>, q.v. </note> 
```

This is because we are not storing the pre-rendered HTML in Solr, but rather the link target and link text in the field, separated by the pipe:

```
"http://example.com/person/123|Person 123"
```

This format has no provision for carrying 'head' and 'tail' information, so given the second example we would have a link that would say "William North, vicar of Saltby" but lose the "Perhaps to be identified with" and ", q.v. ".

**Comment by holfordm** [comment]
Understood. In the second example, it's probably better to keep the full text and lose the link.

**Comment by holfordm** [comment]
@andrew-morrison could you have a look at this when you have time? (which I realize may not be for a while!)

**Comment by andrew-morrison** [comment]
It would help if you could list all the the subfields potentially found in each record which you'd like to have displayed.

Here's what's currently in each (element names only so if they also have attributes that would determine whether or not to display something, please add those):

persons.xml
```
  38030 persName
  17149 ref
   5639 note
   2621 death
   2233 birth
   1415 floruit
    428 residence
    314 bibl
     58 affiliation
     43 sex
     22 occupation
```
works.xml
```
  31846 note
  28253 title
  10661 bibl
  10564 textLang
   5133 author
    225 ref
```
places.xml:
```
   2544 placeName
   1186 ref
    854 orgName
    543 note
    463 location
    463 geo
    338 country
    224 affiliation
     29 bibl
     28 settlement
```
What @ahankinson said about links still applies - only those `ref` elements with a `@target` and a `title` and exist inside `list` elements could be turned into links, the rest will be stripped of all child tags and just display as plain text.
 
Some of the other TEI catalogues have links to VIAF or LCSH URIs, so code to add those would be reusable. The rest would be a Medieval-only enhancements for the foreseeable future.

**Comment by holfordm** [comment]
* persons.xml: display `<bibl>`, `<note>`. `<note>` without `@type` and `bibl`, display as text (there is some formatting of titles which will get lost here, which is a shame; is there any way to get `<title>` in these elements to render italic?). 
`<note type="links">` should generate a list of links.

* works.xml: display `<bibl>`, `<note>`, but NOT `<note type="shelfmark">`.  `<note>` without `@type` and `bibl`, display as text (there is some formatting of titles which will get lost here, which is a shame; is there any way to get `<title>` in these elements to render italic?). 
`<note type="links">` should generate a list of links.

* places.xml: (1) `<place>` entries: display `<location>`, `<note>`. `<note type="links">` should generate a list of links. (2) `<org>` entries: display  `<location>`, `<note>`. `<bibl>`, `<note type="links">` should generate a list of links

I think that should do it...

**Comment by andrew-morrison** [comment]
Now all `title` elements in `note` and `bibl` elements are italicized.

**Comment by holfordm** [comment]
Thank you - this looks great. Regarding the order of material, I think manuscripts should come last, since if there are a lot of manuscripts, the other information is hidden (e.g. http://medieval-qa.bodleian.ox.ac.uk/catalog/person_66806872)

**Comment by andrew-morrison** [comment]
How about this order:

1. Location (places/orgs only, if coordinates are recorded)
2. Notes (if any)
3. References (if any, maybe rename to Bibliography?)
4. External links (if any)
5. See also (if any)
6. Manuscripts (always at least one)

**Comment by andrew-morrison** [comment]
This order is on QA. There's still a few tweaks to the scripts I'm working on to help with #148. Let me know if you want to go live with this next week.

**Comment by holfordm** [comment]
It strikes me that the external links can be a bit cryptic (e.g. if you don't know what VIAF is), and I should give them more meaningful labels (e.g. 'VIAF (Virtual International Authority File) authority record'). What would be the best way to do this? Changing the title field in the links themselves seems unnecessary and would add to the length of already long authority files. Can we supply the fuller form in the XQuery or maybe in the `teiheader` of the authority files, maybe in `encodingDesc`?

**Comment by andrew-morrison** [comment]
Here are the acronyms used in `ref/title` elements in the authority files:

BNF
CERL
DARE
DNB
GND
LC

**Comment by andrew-morrison** [comment]
An alternative would be to use entity references. They're not fashionable these days, but this is precisely what they're intended to allow. For example, if you change persons.xml so it has this...
```
<!DOCTYPE TEI [
    <!ENTITY viaf "VIAF (Virtual International Authority File)">
    <!ENTITY loc "Library of Congress">
]>
```
...between the last of the xml-models and the root TEI element, and search and replace `>VIAF<` with `>&viaf;<`, and `>LC<` with `>&loc;<`, then any XML parser will do the substitution as it loads the file into memory, before any XQuery or XSL is run. No change would be needed to the indexing scripts.

The advantage is you could maintain it yourself. The disadvantage is it is easy to break it, if you get the syntax wrong.

**Comment by ahankinson** [comment]
It would probably be easier if you added xml:id to the category tags and the referenced them with has fragments. I'm not sure if you can do `class=#dnb` or not though.

**Comment by andrew-morrison** [comment]
I think this might be getting more complicated than necessary. We want a solution that, if possible, works for everyone, without adding to the list of things we need to train maintainers of the other TEI catalogues to do.

It is only really an issue for the common acronyms. For example, ARLIMA was one I listed above, but it has actually only been used once.

Here are the common ones:

   3053 VIAF
   2435 GND
   2100 LC
   1761 SUDOC
   1573 BNF

If I hardcode those five in the XQuery scripts, so they're automagically converted during indexing, the rest can been expanded in-place, using Oxygen search and replace, without adding significantly to the file size.

Let me know if that sounds reasonable.

**Comment by holfordm** [comment]
OK, this makes sense. Any documentation I provide of the abbreviations in the TEI itself can be separate from the processing.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by holfordm** [comment]
Happy with this. Any other cryptic external authorities (for example) will be expanded in the authority files. Feel free to close when ready.
