### ISSUE TITLE
Reindent XML across repository

### ISSUE THREAD

**Issue by adunning** [bodleian/medieval-mss#358]
Could we run a reindentation operation on the repository to reformat the XML? This would help to clean up a number of areas, e.g. the mess that `<revisionDesc>` tends to be in and the extra spaces around some tags such as `<author>`.

For that matter, removing the indentation entirely would make it easier to track changes, unless people feel it is instrumental to keeping it readable.

**Comment by andrew-morrison** [comment]
You can do this in Oxygen by right-clicking on the _collections_ folder and selecting **Format and Indent Files...** then wait as it processes all the files within. If you want to remove all indentation (although I personally find it useful) first go to **Options > Preferences**, search for _Indent size_, and set it to zero. Do **not** run it on the entire _medieval-mss_ folder or the _processing_ subfolder.

This will modify almost every TEI file, which would increase the size of the GitHub repository as it keeps a record of every line changed in every file, but it would make viewing the differences in commits and pull requests easier in the future. It wouldn't/shouldn't add spaces between tags and text, so probably won't affect formatting on the web site.

The timing of when to do this is important. To avoid conflicts, it would be best to tell everyone who might be working on the records when you plan to do it, and ask them to commit/push/submit-pull-a-request before that date. Merge any pull requests before doing the reformatting. Then, afterwards, tell everyone to update their local copies before starting work again. For people whose local copy is cloned from the original Bodleian repository, they just need to pull the changes. For anyone using a fork, they'll need to bring it level with the original. I've written [some instructions](https://github.com/bodleian/medieval-mss/wiki/Updating-a-fork) that hopefully would help, but there's always the potential that someone's individual setup will cause problems.

Alternatively, you could have a policy that everyone should run the format and indent on a collection's subfolder, and commit and push, before starting work on the records within.

**Comment by adunning** [comment]
I've got the settings down now to keep things the same as much as possible. Would it make sense if we did this just before the holidays, @holfordm?

**Comment by holfordm** [comment]
What exactly do you have in mind?

**Comment by adunning** [comment]
I was thinking of Andrew's proposal to run the Oxygen reindent operation on the entire project. I do still wonder if removing the indentation would make life easier in terms of allowing cleaner diffs: the display of <https://github.com/bodleian/medieval-mss/pull/387/commits/1b34c83c1cba2bd996fd9346e658d859cc02bf02> is a good example.

**Comment by holfordm** [comment]
Would removing indentation make the files difficult to use as an editor though? I'd also be keen to test this on a single small repository before applying it generally, to check that it won't have any unintended consequences in terms of introducing whitespace.

**Comment by andrew-morrison** [comment]
If you do a test tomorrow on a subfolder of _collections_, after I have re-indexed production with the latest updates this evening, then I can re-index QA so you can compare. Try to pick something with lots of corrections and/or notations.

I'm not sure what the effect of removing indentation would be on the clarity of diffs. It compares on a line-by-line basis, with no understanding of XML, hence why it sometimes confuses a moved child element for an edited close-tag.

**Comment by holfordm** [comment]
We can try reformatting one collection with indentation and one without?

**Comment by andrew-morrison** [comment]
I have re-indexed, so go ahead. Make sure to choose collections which don't contain any files currently with changes in unmerged pull requests.

Another formatting issue you might like to standardize is the order of _notBefore_ and _notAfter_ attributes. To do so, right-click on the collections folder, select Find/Replace in Files..., then fill in the form as in the screenshot below (or the opposite if you'd prefer notAfter to precede notBefore):

![find_replace_in_files](https://user-images.githubusercontent.com/33721187/101813772-15bd1f80-3b15-11eb-9d86-08ed053ef528.png)

**Comment by holfordm** [comment]
Andrew has persuaded me that this test isn't necessary, so he's going to run the reformatting across all the collections on Monday 21 Dec.

**Comment by andrew-morrison** [comment]
As well as merging open pull requests before doing this, as a final step it would be a good idea to review the active branches listed here:

https://github.com/bodleian/medieval-mss/branches

**Comment by adunning** [comment]
Thanks, @andrew-morrison – great idea to fix notBefore/notAfter. I suppose we might as well test on one collection.

**Comment by adunning** [comment]
We're nearly at the point of having all the active branches cleaned up. I believe @holfordm has identified `<choice>` and `<subst>` as elements within which space should be preserved – are there any others?

I've added an Oxygen project file to synchronize the appropriate indentation settings in <https://github.com/bodleian/medieval-mss/commit/b65059811b0b6b4ddfd764d20e332bf831ab592d>.

**Comment by adunning** [comment]
I've added a test collection in #434.

**Comment by adunning** [comment]
Closed in <https://github.com/bodleian/medieval-mss/commit/e282fe327a3413c7407b0e39c86fdad8d522874b>.

**Comment by andrew-morrison** [comment]
I have re-indexed the QA server so, if you want to do some random sampling, you can compare the effects of formatting changes with production. Unless I hear otherwise, I will re-index production at the end of Thursday.

[One of the changes](https://github.com/bodleian/medieval-mss/commit/9b9a12eb8754fba528c1ce70a8f8b5d48e4127ac) you made on Friday has created 674 new validation errors, in every Merton, Exeter and St. John's record, because `funder` is not allowed to be the first (or only) child of `editionStmt`. Please fix those before closing this issue. And validate before committing bulk changes in the future.

You reformatted the _processing_ folder. [I said above](https://github.com/bodleian/medieval-mss/issues/358#issuecomment-698922915) not to do so. The XQuery scripts in particular are less legible, and I have neither the time nor the inclination to retest everything, so I have undone the changes in the _processing_ folder.

It is worth noting, for future reference, that all the changes made on Friday added 133 MB to the size the repository (at least in my local copy) due to every modification to every line having to be stored in the _.git_ subfolder.
