### ISSUE TITLE
provide help and about pages

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#36]

**Comment by IgnatG** [comment]
any updates on this?

**Comment by holfordm** [comment]
Nearly there! Should there be some details about the technical side? Can we keep the pages in the repo somewhere?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by IgnatG** [comment]
I think it's up to you. We can include another page that contains just the technical part or we can include it in one of the existing pages.
I think we can put it on the repo here. @ahankinson what do you think?

**Comment by ahankinson** [comment]
I would rather not keep non-catalogue text files in the repo...
