### ISSUE TITLE
numerical identifier rather than shelfmark in manuscript URLs?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#38]
URLs for manuscripts are currently in the form `catalogue/manuscript_MS_Add_A_1` and so on. Are we planning to switch to using the numerical identifier `catalogue/manuscript_xxxxxx` ?

**Comment by ahankinson** [comment]
That would be ideal, but it should be done ASAP.

**Comment by holfordm** [comment]
What is required at my end? The identifiers should all be in place: `xml:id="manuscript_xxxx" `on the root `<TEI>` element.
