### ISSUE TITLE
decoNote @type

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#4]
decoNote/@type:
diagrams to 'diagram' -- OK

borderInitials,  initial_border -- these are for when I have one decoNote with a short note on all the ms decoration, e.g. "Border, initials", and I want to record both types. Separating the types with underscore seems like the best approach?

frieze: no comment, don't think I use.
paratext, printmark, secondary, unspecified or uwan - don't think I use. Would be careful of normalizing, some of these sound meaningful.

**Comment by jamescummings** [comment]
The numbers at the time of writing the report were: 
````
type (690) ="border (20) | bordersInitials (1) | decoration (71) | diagram (23) | diagrams (1) | frieze (1) | illustration (91) | initial (51) | initial_border (1) | initials (9) | marginal (6) | marginalSketches (1) | micrography (23) | miniature (7) | other (66) | paratext (1) | printmark (1) | rubrication (184) | secondary (2) | unspecified (59) | unwan (71) "
````
So paratext/printmark/secondary are a total of 4 notes in all oxford collections... I thought standardisation might be better. I've changed it so unwan goes through.

re: underscore; so we have border, bordersInitials, initial, initial_border and initials.  I would have said when the decoNote is a general note, not on a specific aspect of the decoration, then don't classify it at all. i.e. get rid of bordersInitials and inital_border entirely.   But yes, we could standardise to some combined form if you prefer.

**Comment by holfordm** [comment]
Let's use initial_border for combined forms with the principal being that if there is more tha one type of decoration, the different types are separated by underscore. I haven't classified decoration in detail yet, and probably won't have the time, but I would like to set things up so that the material we have can at some future point be classified along these lines.



________________________________

**Comment by jamescummings** [comment]
I believe this is done, so I'm closing it. re-open if it is still a problem.
