### ISSUE TITLE
Filename for Fragments

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#42]
The file `Fragments_printed_books/A_1_11_Art_Seld_pastedowns.xml` should be renamed to `MS_A_1_11_Art_Seld_pastedowns.xml`.

**Comment by ahankinson** [comment]
Assigning Matthew & James since it's possible that this is not a simple renaming process.

**Comment by holfordm** [comment]
This folder is for manuscript fragments in printed books (a small cataloguing programme that is in progress as part of the "fragmentarium" project). The shelfmark therefore really is "A 1 11 Art Seld, pastedown". "A 1 11 Art Seld" is the shelmark of a printed book and the ms fragment that the description is concerned with, is a pastedown in the binding. Does this make sense?

**Comment by ahankinson** [comment]
Yes, it makes sense -- the filenames and the XML IDs need to be standardized, though.

**Comment by holfordm** [comment]
Feel free to make any necessary changes now and perhaps we can discuss the standardization principles when I'm back in Oxford? I had been thinking that the "manuscript_xxx" xml:id was the imporant bit...

**Comment by ahankinson** [comment]
My understanding was that James' normalization process was making the filenames and the xml:ids match.

**Comment by holfordm** [comment]
James add two xml:ids to each descrption (a) on `msDesc,` this is the same as the normalized filename (b) on `TEI,` this is in the form "manuscript_xxx", and I think for consistency we should use (b) for the URLs and indexing, cf issue [28](https://github.com/bodleian/medieval-mss/issues/38)

**Comment by holfordm** [comment]
since we have switched to using numeric IDs, can this be closed?

**Comment by jamescummings** [comment]
It was making the filenames and IDs match, but if needing it changed now then it should be done manually.

**Comment by holfordm** [comment]
Modified schematron now checks that ID and filename match
