### ISSUE TITLE
home page: two "Ashmole" collections

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#43]
There are two collections named "MSS. Ashmole" on the home page. One of these should be "MSS. Ashmole Rolls".

**Comment by ahankinson** [comment]
We're having to jump through some hoops to get these collections to display correctly on the front page. We have to inspect the value of the parenthetical statement and substitute that in for the "non-expert" friendly name. This is why it keeps breaking.

It would be far easier if we could just index the full name directly from the TEI. So, "MSS. Canon. Class. Lat. (Canonici Latin Classical)" would become "MSS. Canonici Latin Classical". This would be much less fragile.

**Comment by IgnatG** [comment]
Yeah. that's very true. if we can get them in full version, well... that would be great! - it is a workaround now...

**Comment by holfordm** [comment]
Can we use the current style "MSS. Canon. Class. Lat. (Canonici Latin Classical)" for display on the home page? It would take up more room of course. But it would have the big advantage of keeping the "correct" form of the shelfmark (the abbreviated form is how the MSS are supposed to be cited and ordered).

**Comment by IgnatG** [comment]
That would be the easiest approach. The problem would be the fact that they are too long - say "MSS. Holkham misc. (Holkham miscellaneous)" for instance. But I guess we can give that a try and see how it goes.

**Comment by holfordm** [comment]
Let's try it out

**Comment by ahankinson** [comment]
Done. 

I think Gabriel's right -- it does look a bit messy to my eye. What do you think?

**Comment by holfordm** [comment]
Yes, it is messy. But can we leave it as is for now? I'll discuss with Martin as to whether the short or long titles are better here. He is back from holiday mid-week.

**Comment by ahankinson** [comment]
Closing for now.
