### ISSUE TITLE
person and place pages using "classmark" urls for manuscripts

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#44]
ie. the links on person and place pages lead to `../manuscript_MS_Germ_g_1` rather than` ../manuscript_xxxxx`

I'm sure you are aware of this but flagging just in case

**Comment by holfordm** [comment]
fixed for persons but not for places

**Comment by ahankinson** [comment]
The commit fixed it for places, I just didn't get a chance to update it on the QA site.
