### ISSUE TITLE
en dashes in manuscript shelfmarks

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#449]
@adunning the change from the minus sign to en dash in ranges of numbers seems to have broken links to Zotero in manuscripts with shelfmark-ranges, e.g. MSS. Douce 219-20. This needs to be fixed either by restored the shelfmarks in the TEI to their previous form or by changing the tags in Zotero - whatever we decide is the most sustainable.

**Comment by holfordm** [comment]
The simplest solution is to revert the en dash to the minus character in the relevant contexts in TEI. @andrew-morrison  - could you confirm which element is used to call the Zotero API?

**Comment by andrew-morrison** [comment]
The tag sent to Zotero is the page title. In the medieval catalogue, that is the first child `idno` of type "shelfmark" in the `msIdentifier` (the overall one, not ones in `msPart`). There are currently 114 of those which contain en dashes.

**Comment by holfordm** [comment]
closed by 7ffe24496a9a4e98947d314f9cd86017967132e4
