### ISSUE TITLE
person browse list should filter by role

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#46]
- each person record would be associated with a collection of their roles throughout the collection (author, scribe or scribe, owner for example)

- these roles would provide a filter

- most roles are` persName/@role` but role=author has to be inferred from `<author>`

**Comment by ahankinson** [comment]
I'm getting values like `formerOwner`. I'm assuming you don't want that displayed? What are the list of possible roles, and how would you like them to be expanded?

**Comment by holfordm** [comment]
Mapping below.

Note also that `@role` may contain multiple roles separated by whitespace

[roles-map.txt](https://github.com/bodleian/medieval-mss/files/1138976/roles-map.txt)

**Comment by ahankinson** [comment]
I'm going to guess that you want these roles capitalized?

**Comment by holfordm** [comment]
I had thought not but since the facets on manuscripts are currently capitalized we should do the same here for consistency
