### ISSUE TITLE
tidy up publicationStmt

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#5]
sort out duplicate appearance of Bodleian Library / Libaries in `<authority>` and `<publisher>`

**Comment by jamescummings** [comment]
What should be the perfect publicationStmt?  i.e. we should probably include full address and contact email for manuscripts (generally) in the Bodleian.  Suggestions as to what that should be appreciated.

**Comment by holfordm** [comment]
good question. I suggest something like:

```
<publisher>Bodleian Library, Special Collections</publisher>
<address>
<addrLine>Weston Library</addrLine>
<addrLine>Broad Street</addrLine>
<addrLine>Oxford</addrLine>
<addrLine>OX1 3BG</addrLine> 
<addrLine>United Kingdom</addrLine>
<addrLine><email>specialcollections.enquiries@bodleian.ox.ac.uk</email></addrLine>
</address>

```
but your opinion as ever is welcome and there may be better places for the different elements to go. Is publisher Ok or do you prefer authority? Should we include a date?
I have talked with Martin about licences and he is investigating what the library will permit.

**Comment by jamescummings** [comment]
How about something like this:
````
<publicationStmt>
<publisher>Special Collections, Bodleian Libraries</publisher>
<address>
 <orgName type="department">Special Collections</orgName>
 <orgName type="unit">Bodleian Libraries</orgName>
 <orgName type="institution">University of Oxford</orgName>
 <street>Weston Library, Broad Street</street>
 <settlement>Oxford</settlement>
 <postCode>OX1 3BG</postCode>
 <country>United Kingdom</country>
</address>
<distributor>
 <email>specialcollections.enquiries@bodleian.ox.ac.uk</email>
</distributor>
<availability>
 <licence target="https://creativecommons.org/licenses/by/4.0/">A Creative Commons Attribution licence applies to this file.</licence>
</availability>
<idno type="website">manuscript_12345</idno>
<idno type="msID">MS Foo Blort 123</idno>
<idno type="collection">Foo</idno>  
</publicationStmt>
````
Major changes are to use specific elements rather than addrLine, include the email as distributor (though I suppose this could be authority), include an availability and some idnos that are easy to add.

**Comment by holfordm** [comment]
We can't include a licence yet, I don't yet know what type we can use. 
It seems odd to have `distributor/email` separate from `publisher`.
idno type="shelfmark" instead of "msID"?
idno type="URI" instead of "website" (giving the whole URI)?

**Comment by jamescummings** [comment]
Leaving this issue open to remind us that we need to get a consistent bodleian open licensing for the manuscript description.

**Comment by holfordm** [comment]
closed. licence is now issue [56](https://github.com/bodleian/medieval-mss/issues/56)
