### ISSUE TITLE
organizations missing from place index

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#52]

**Comment by ahankinson** [comment]
I am currently working on the indexing systems, so what you see reflected in the QA site is not the "truth," insofar as organizations *will* be indexed in places, but may not be at any given moment in development as I clear and re-do the indexing to work through issues.

If you look in the 'processing' folder you will see that there is an xquery file for organizations, and that this file does index them as places:

https://github.com/bodleian/medieval-mss/blob/master/processing/organizations.xquery#L22
