### ISSUE TITLE
problem with searching persons?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#58]
in 'persons', a search for 'salisbury' 
http://black01-qa.bodleian.ox.ac.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=person&q=salisbury
does not return 'john of salisbury' [i.e. http://black01-qa.bodleian.ox.ac.uk/catalog/person_67145970022632250570 , whose display title is "John, of Salisbury, Bishop of Chartres, -1180"]. Similarly no results for "bishop of chartres".

**Comment by ahankinson** [comment]
Major improvements to fulltext searching went live on QA today, and this now works.
