### ISSUE TITLE
surrogates that are not digital images

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#596]
I don't think that a `surrogates` element for non-digital images will currently display -- but it would be very useful, for some restricted items where we have microfilm but no digital images, to indicate this in the catalogue.

Suggested markup would be something like this:
` <surrogates>
    <bibl type="microfilm">Microfilm available on open shelves (R. Films 101)</bibl>
</surrogates>`

**Comment by andrew-morrison** [comment]
The XSLT is already set up to handle that markup:

https://github.com/msDesc/consolidated-tei-schema/blob/5137720d39ec8c2ba3ad0cccb1018cc88c3e48f8/msdesc2html.xsl#L2194-L2204

That was implemented for the Hebrew catalogue, and here is an example of the resulting HTML:

https://hebrew.bodleian.ox.ac.uk/catalog/manuscript_211

You could alternatively wrap the shelfmark of the microfilm in an `<idno>` tag and give that the `type="microfilm"` attribute. Or both. You can verify the syntax works by previewing in Oxygen.
