### ISSUE TITLE
Subjects start with #

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#60]
Is this desired?

**Comment by holfordm** [comment]
No, it is a relict from how the subjects were described in `msDesc`; feel free to delete the `#`

**Comment by ahankinson** [comment]
They should probably be removed from works.xml... would it be OK if I did that?

**Comment by holfordm** [comment]
Yes, please remove them from works.xml.  I will delete works-without-authors and works-without-authors from the repo later today, they are no longer needed.

**Comment by holfordm** [comment]
ps please let me know when you've finished, there are some changes I need to make to the file. Or I can remove the # myself if you like.

**Comment by ahankinson** [comment]
I'm working on some infrastructure things today (getting the names of the TEI servers sorted out) so if you're working on that file feel free to remove the #s and commit.

**Comment by holfordm** [comment]
closed via c9094adb2e460691d1d4446036b6cb75a145963c
