### ISSUE TITLE
Display of item numbering in composite manuscripts where one unit only contains one item

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#618]
Comment in relation to St John's College MS. 113 from the St John's cataloguer

"it seems that if there is only one item in a manuscript then the item number does not show. For MS 113, this means that the only text in the second manuscript is not listed as item 4, whereas it is listed as item 4 in Hanna’s original. Do you think this is an issue? It is encoded as item 4, but this is simply implied for the website user. " 

For another example see https://medieval.bodleian.ox.ac.uk/catalog/manuscript_10117 where the item number "29" is missing from part II. 

We can discuss if the logic for fixing this is not immediately  obvious!

**Comment by andrew-morrison** [comment]
I've made changes to the logic for whether to display the numbering, and re-indexed the QA server. Now it will display numbers on works when there are different values for `@n` attribute on msItems at the same level (i.e. depth in the XML hierarchy.) So it won't display "1" for every work in a composite manuscript where each part has one work numbered "1". But it will display work numbers if the sequence continues across parts in all parts, or if any one part contains multiple numbered works.

Please take a look and close this issue if you're happy. It affects 488 records in Medieval. Attached is a list:

[diff.txt](https://github.com/bodleian/medieval-mss/files/9491271/diff.txt)

It does reveal some possibly incorrect numbering schemes that have previously been hidden. For example:

- MS_Bodl_50.xml contains three msItem, numbered 1, 2, 1, in three parts.
- MS_Bodl_514.xml contains nine msItem, numbered 1, 2a, 2b, 2c, 2d, 3, 4, 5, 1, in seven parts.
- MS_Ashmole_794.xml contains five msItem, numbered 1, 2, 1, 1, 1, in five parts

**Comment by andrew-morrison** [comment]
Have you had a chance to look at this change to numbering? If so, should I re-index PRD later today with changes to the XSLT, or the old version?

**Comment by adunning** [comment]
I almost wonder whether we could simply do away with item numbers: do they serve any purpose when there are folio references? Sometimes people accidentally cite them, mistakenly thinking that they are a stable identifier, since earlier print catalogues sometimes used them this way.

**Comment by holfordm** [comment]
@andrew-morrison I'm afraid I didn't get a chance to look at it (apologies) and I'm currently without access to the QA site. I shall look at it early next week.
