### ISSUE TITLE
Multiple <msName> elements do not display correctly

### ISSUE THREAD

**Issue by adunning** [bodleian/medieval-mss#622]
If there is more than one `<msName>` element, they display together in a single line with no punctuation.

This is currently visible in [MS. Laud Misc. 678](https://medieval.bodleian.ox.ac.uk/catalog/manuscript_7460):

<img width="666" alt="Screenshot 2022-09-13 at 11 16 42" src="https://user-images.githubusercontent.com/1084407/189876359-fe9ca1d0-d804-4a6d-b1e8-b90a3dcf011b.png">

I would expect these to be separated with a line break or semicolon.

**Comment by andrew-morrison** [comment]
I've re-indexed QA with a fix for this, putting each `msName` on its own line. The only other record this affects is MS. Auct. F. 4. 32, which has three of them.

Close this issue if you're happy with the change.

**Comment by adunning** [comment]
Thank you!
