### ISSUE TITLE
fix empty elements with '@key' 

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#64]
empty TEI elements with '@key' e.g. `<author key="person_1"/>` are interfering with convert2HTML - fix the empty elements or the conversion script.

This is fixed for 'author' but MLH needs to see if other empty elements are causing problems.

**Comment by ahankinson** [comment]
I think this still needs to be determined.

**Comment by holfordm** [comment]
The only empty element with `@key` is `<author>` so this can be closed.
