### ISSUE TITLE
font size OK?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#65]
in general in the manuscript records (e.g. http://black01-qa.bodleian.ox.ac.uk/catalog/manuscript_3961) do the font size, spacing, etc., meet accessibility requirements?

**Comment by IgnatG** [comment]
There are a couple of things that can be changed from that perspective. I haven't done much to it yet because Andrew was still tinkering with the content.

**Comment by ahankinson** [comment]
Done tinkering.

**Comment by IgnatG** [comment]
fixed
