### ISSUE TITLE
beta banner

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#67]
I think we should have a beta banner somewhere on the site. It might contain or lead to a link asking for feedback This would be removed when the whole suite of TEI catalogues launches. What do you think?

**Comment by IgnatG** [comment]
I think this will be nice to have but I'm not sure if I have the time to do it this week. It will probably have to be done when I'm back (which is presumably after the launch).

**Comment by ahankinson** [comment]
I wouldn't want this. "Beta" implies unfinished, but this will probably never be "finished."

**Comment by holfordm** [comment]
In terms of data it will never be finished and there will be a constant process of improvement, but in terms of functionality there will be (I guess) far fewer and less frequent changes. Beta seems appropriate to me with reference to the functionality of the site if we are planning a user review of the TEI sites leading to later improvements, which I had thought was part of the TEI consolidation plan, though I may well be wrong about that.

@ahankinson would you be in favour of any record of signficant changes to data/functionality (other than git)?

**Comment by ahankinson** [comment]
I would still not advise a "beta" banner. A reason for my hesitation can be found here:

http://scores.bodleian.ox.ac.uk

This site has been in "beta" for about five years now, with slim chance that it will ever get out of beta short of a rewrite of the site. I don't think the badge adds anything to the site other than advertising our own insecurity about our work. It's the modern equivalent of the "Under Construction" animated GIF. It provides no real information to our visitors, and its sole purpose seems to be to try and absolve ourselves from any data problems or lack of functionality. ("I'm sorry it's broken, but it IS in beta...")

For "record of significant changes" do you mean having a versioning system (1.0, 1.1, etc.)? Yes, I would be in favour of that.

**Comment by IgnatG** [comment]
Oh no! not that badge...
I thought you were thinking about something along these lines: [https://botsify.com/](url)- that "thing" at the bottom right. - similar to a chat bot, except that we won't necessarily have a conversation with them, but we would just ask for feedback.

**Comment by IgnatG** [comment]
and yes, I would go for the versioning as well if needed

**Comment by holfordm** [comment]
I completely see what you mean. 
I was thinking of something like this https://www.gov.uk/service-manual/design/alpha-and-beta-phase-banners
Perhaps (without using the dreaded beta word) we could say something like 'we are carrying out user evaluation on the site until [date] and your feedback will help us improve it'. If we are planning user evaluation of course!

**Comment by ahankinson** [comment]
Would this be different from the contact form that is on each page?

**Comment by holfordm** [comment]
I think there is a difference between making comment possible and actively encouraging it. Whether we do both for a time depends in part on whether we are having a period of user testing.

**Comment by ahankinson** [comment]
I will leave this to @IgnatG to decide.

**Comment by IgnatG** [comment]
I think that's a valid point. But if we are going to conduct a user testing - which I assume I'm part of or I'm conducting (with Frankie), then we will have to do it differently. This means bringing users in and watching them do things on the website. And since we bring them in, we can also conduct a usability test and an eye tracking one. 

The feedback button on the actual page would act only as a feedback for us in case they like something or not. And the contact us button will be used I guess for telling us something else - general questions I assume.

**Comment by holfordm** [comment]
It sounds like we do not need a separate feedback button for now.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
