### ISSUE TITLE
Move respStmt from editionStmt and tidy up ENRICH mentions

### ISSUE THREAD

**Issue by jamescummings** [bodleian/medieval-mss#7]
Hi @holfordm,

Unless you object I'm going to move the respStmt with your name attached that says "Conversion to TEI based on earlier work for the ENRICH project..." and instead break these into separate respStmts in titleStmt which is more usual.  This will also enable me to update the ENRICH information which is out of date.  I propose:

````
<!-- any existing respStmt  then -->
<respStmt>
  <resp>Improvements to manuscript descriptions content and markup</resp>
  <persName>Matthew Holford</persName>
</respStmt>
<respStmt>
  <resp>Earlier work for ENRICH project <ref target="http://projects.oucs.ox.ac.uk/ENRICH/"
      >http://projects.oucs.ox.ac.uk/ENRICH/</ref> or <ref target="http://enrich.manuscriptorium.com"
      >http://enrich.manuscriptorium.com</ref> converting EAD records to TEI. </resp>
  <resp>Up-conversion of TEI files to bodley-msDesc schema in 2017</resp>
  <persName>James Cummings</persName>
</respStmt>
````
If you want to let me know either other people who should be credited with things concerning the msDesc file and what you want your resp(s) to be. (You can have more than one responsibility, clearly...)  Specifically with ENRICH I wanted to point to the two new locations since tei.oucs will disappear when I leave and remove the email address (since we're no longer listening to that one).

**Comment by holfordm** [comment]
I think this is a good idea, but I also would like to wait a bit before doing it to finalize with Martin the exact details of attribute (e.g. including the attributions to Elizabeth Solopova, whether the earlier funding by the Getty foundation should be mentioned, etc. etc.) - so can we hold fire on this for the moment?

**Comment by jamescummings** [comment]
Sure, I mean I've put it in the conversion as it stands but can take it out (if it is a problem) or update it at any point.  We could also use 'funder' to record details of who funds it but that is of course a bit strange for something like manuscript descriptions that might hang around for years and be worked on by various funded projects funded by different bodies.

**Comment by jamescummings** [comment]
Another related issue: Should the editionStmt/respStmt be the same for all the Western MSS? Or are some different one way or another. Easy way to tell?  A simplified edition element might have something like "TEI P5" and a date.  Unless, of course, you wanted to introduce catalogue version numbers or something.

**Comment by holfordm** [comment]
I think the editionStmt can be consistent across all collections and should be TEI P5 + version number (good idea) + date

The respStmt varies from collection to collection depending on who created the original description.


________________________________

**Comment by jamescummings** [comment]
Closing since editionStmt has been normalised but responsibility structure and practice should be investigated across all catalogues so handled the same.
