### ISSUE TITLE
display issue in Internet Explorer

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#73]
The page header and footer aren't rendering correctly in internet explorer. I have been told that this also affects Safari but haven't seen that myself. Chrome and Firefox are fine.

**Comment by IgnatG** [comment]
This was fixed on my end a while ago. It just needs updating on the actual webpage. It looks like it works fine in IE10. But it crashes in IE 11....

**Comment by holfordm** [comment]
medieval-qa seems to be working fine in IE 11 for me...

**Comment by IgnatG** [comment]
it should work fine also on the main website.
