### ISSUE TITLE
bug in print stylesheet?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#74]
using Mozilla - when printing a multipage record, only the first page prints. 
e.g.: https://medieval.bodleian.ox.ac.uk/catalog/manuscript_10000

This does not affect Chrome. I haven't tested other browsers.

**Comment by IgnatG** [comment]
It looks like it's just a Firefox issue. this has been fixed on my end. It will be updated on the actual web page when Andrew is back - I think
