### ISSUE TITLE
improve display of `additional/listBibl`

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#75]
see https://medieval.bodleian.ox.ac.uk/catalog/manuscript_1097

**Comment by holfordm** [comment]
2. has been fixed by @IgnatG  in CSS.
1. has partly been fixed by @ahankinson via d852e3bea47d5f222e807c5b87133445acdd46d7 - however, the heading still renders differently from the other main headings ('Record Source', etc.). Presumably this is because of  the tei-label class? Would it be best to (a) have no class (cf. Record Source) or (b) have class="msDesc-heading3" (as with the History heading).

sample record
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_10000

**Comment by ahankinson** [comment]
I think (b) would be the best option.

**Comment by holfordm** [comment]
fixed via ed985774fecb37f8a4508013b10b30bc93fc3b13
