### ISSUE TITLE
filter text displays awkwardly on small screens

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#81]
e.g. https://medieval.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=manuscript, filtering by origin, filters include: 
Byzantin
e Empire
Luxembu
rg
where filters are divided mid word into multiple lines.
There are similar problems in the Language filter and, especially, in the Collection filter - if possible, the filter text here should be shorter (just the short title, not short + expanded).
Is there anything that can be done to improve this?

**Comment by IgnatG** [comment]
I was trying to replicate the issue but I can't see it immediately. Can I ask what screen size it was? Was it a mobile phone? Or directly in the browser?

**Comment by holfordm** [comment]
It is an issue in Chrome and Mozilla when the browser is small enough (e.g. when it is half screen size). The filters actually look fine on mobile. Will check on tablet later...


________________________________

**Comment by IgnatG** [comment]
done. This should show up on the actual website soon
