### ISSUE TITLE
div.form, .support, .extent, .dimensions should have margin-bottom 5px ?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#82]
sample record:
https://medieval.bodleian.ox.ac.uk/catalog/manuscript_3971

I think it would improve legibility of the record if these elements had the same bottom margin as .secFol

**Comment by IgnatG** [comment]
//done; double check and re-open issue if needed

**Comment by holfordm** [comment]
The spacing between `extent` and `dimensions` remains irregular (e.g. http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_3962). This was my mistake in specifying the issue. Because the dimensions `div` is nested inside the extent `div`, both together only have one bottom border. To fix this we need to give `div.dimensions` `margin-top` of 5px rather than `margin-bottom` 5px.

**Comment by IgnatG** [comment]
//fixed. It should be reflected on the next update
