### ISSUE TITLE
.super interferes with line height?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#83]
sample record: https://medieval.bodleian.ox.ac.uk/catalog/manuscript_3971

the superscript characters appear to cause irregularity in the line spacing.

**Comment by IgnatG** [comment]
//done; double check and re-open issue if needed. 
// this applies to all other as well: at the moment I've pushed the changes to the repo. They should go live soon.

**Comment by holfordm** [comment]
Not sure this has been resolved - e.g. http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_3962, particularly in the collation and provenance sections

**Comment by IgnatG** [comment]
//fixed. It should be reflected on the next update
