### ISSUE TITLE
redirects from old site?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#86]
There are still quite a few references to the old site on search engines. 
Search for "Lat liturg f 23" and you will see what I mean.
It would be great if these could be redirected to a page that said something like "You have followed a link to an older version of this site, you will be redirected to the new version shortly" (followed by a redirect).
The relevant URL patterns seem to be `medieval.bodleian.ox.ac.uk/profile/.`* and `medieval.bodleian.ox.ac.uk/source/.*`
Is this feasible?

**Comment by ahankinson** [comment]
As far as I can tell the identifiers used on the old site are ephemeral, and don't actually exist in the TEI data. So there is no way to link:

http://medieval.bodleian.ox.ac.uk/profile/manuscript/87707656-0722-4f8f-83c1-bc44cacb946c

with 

https://medieval.bodleian.ox.ac.uk/catalog/manuscript_6532

even though the point to the same record.

I think the best thing to do is to try and drop all the documents as fast as possible from Google's search index. I've signed us up for Google's Search Console, which lets me manage how it indexes this content, so hopefully we'll see some changes soon.

**Comment by holfordm** [comment]
That is correct about the identifiers. It would have to be a general redirect from a URL pattern to say the home page of the new site. But the search console approach sounds simpler.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ahankinson** [comment]
Search console stuff was implemented a long time ago, and results are now appearing in Google's index.
