### ISSUE TITLE
Propose changing the repo title

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#9]
Since this is the repository for Western manuscripts, I think we should probably change it to `tei-western` or `tei-western-mss`. @holfordm, @jamescummings thoughts?

**Comment by jamescummings** [comment]
Why not bodley-western or since under bodleian organisation just western-mss or something?  At the moment it looks like only the TEI file should be going in there. ;-)

**Comment by holfordm** [comment]
The alternative to a name based on western is something based on medieval - I don't have strong feelings about it, but medieval would be more consistent with our intended URL


________________________________

**Comment by jamescummings** [comment]
medieval-mss perhaps?

**Comment by holfordm** [comment]
seems accurate and inoffensive!

**Comment by ahankinson** [comment]
OK, I will change it. Note that you will have to change any git clones of the repo to point to the new URL.
