### ISSUE TITLE
remove indentation of ul.listBibl

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#90]
the section ul.listBibl [inside div class="additional"]  is currently indented - I think this indentation should be removed, so the text is flush with the left margin, consistent with the rest of the record.

sample records:
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_1097
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_10000

## Context
This will improve the appearance of the record pages.

**Comment by IgnatG** [comment]
//done
