### ISSUE TITLE
Trailing underscore in ChCh Allestree MS M.1.10

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#93]
## Detailed Description
The xml:id identifier in Allestree MS M.1.10 has a trailing underscore which is breaking the indexing process.

## Link to Page
https://github.com/bodleian/medieval-mss/blob/master/collections/Christ_Church/Christ_Church_Allestree_Library_MS_M110.xml#L42

**Comment by holfordm** [comment]
fixed via f3881dda917a6b72a2858a9721ece955fed3c30a
