### ISSUE TITLE
record source heading to be triggered by source, not additional

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#98]
## Detailed Description
In composite manuscripts, unnecessary 'record source' heading is generated by inclusion of bibliography

## Link to Page
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_675

**Comment by andrew-morrison** [comment]
I've commited [a fix to the consolidated-tei-schema repository](/bodleian/consolidated-tei-schema/commit/da1c3b9d26602779f0cf0dedbe77cf376201663a) (now that the core XSLT for generating manuscript HTML resides there) and refreshed medieval-qa.

The only manuscripts which appear to be visibly affected are the following six:

[Add_A/MS_Add_A_370](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_61)
[Add_A/MS_Add_A_30](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_57)
[Auct_F/MS_Auct_F_4_32](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_675)
[Bodl/MS_Bodl_91](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_1877)
[Auct_D/MS_Auct_D_4_13](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_463)
[Auct_D/MS_Auct_D_2_6](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_438)

They've gone from two "Record Sources" headings to just one, as desired.

I can't check all the rest, but random sampling suggests that the "Record Sources" h3 element is nested deeper into the hierarchy of divs, but will appear in the same place.
