### ISSUE TITLE
problem with results paging in Zotero

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#99]
## Detailed Description
When there are more than 25 results in Zotero, they are spread over multiple pages. Moving from the first page of results currently results in an error whereby the second page of the whole library is displayed.

## Link to Page
https://www.zotero.org/bodleianwmss/items?tag=MSS.%20Douce%205-6 [landing page from our catalogue, http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_4476]

https://www.zotero.org/bodleianwmss/items/itemPage/2 [if you try to advance by 1 page]

## Possible Implementation
searching within Zotero itself now generates URLs in this form:
https://www.zotero.org/bodleianwmss/items/tag/MSS.%20Douce%205-6
where paging functions correctly.

This seems to be a new issue. I guess that Zotero 5.0, which has recently been released, has lead to a change in URL structure, and so we need to change the format of our API requests; however, the documentation on the website has not been updated yet. @IgnatG , would you be able to investigate this further?

**Comment by IgnatG** [comment]
I will have a look at it but I can't do it straight away. I'm distracted with SOLO&ORA (+ Exhibitions) at the moment. It will have to be in January I'm afraid.

**Comment by holfordm** [comment]
Thanks!

**Comment by holfordm** [comment]
@IgnatG is there any chance you would be able to look at this in the reasonably near future - otherwise could it be reassigned? I think it will just be a question of changing the Zotero URL to the new style as above.

**Comment by IgnatG** [comment]
I'll look at it this week - finally got some "time off" from other projects

**Comment by IgnatG** [comment]
//done.
@andrew-morrison can you update QA, please?
@holfordm after the update, can you test it for me please? I've tested on few pages and it looked ok.  Let me know if it's problematic. Otherwise you can close it.

**Comment by andrew-morrison** [comment]
Deploy to Medieval QA web site done.

**Comment by holfordm** [comment]
Thanks both. I've tested it on [MS. Junius 11](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_6318), which has 122 items of bibliography, and it works perfectly: you can now page correctly through results, and also sort results by author, title or date.

**Comment by holfordm** [comment]
closed prematurely (sorry) - reopening as a reminder that this needs to be pushed to prd

**Comment by andrew-morrison** [comment]
Deployed to production.
